#pragma once
// CreatureActionNames — the creature actions that carry a name in the binary.
//
// A creature's plan names a CREATURE_ACTION, of which there are 328
// (NUM_CREATURE_ACTIONS). Each has an 80-byte record in a runtime dispatch
// table at 0x8FFCB8: the name at +0, a handler function pointer at +32, and a
// second code pointer at +52. sub_4B6CA0 dispatches through it.
//
// The table is .bss, filled by a long inlined initialiser around 0x481000, and
// only entries 233..327 have their name slot written -- indices 1..232 are
// never assigned at all, and index 0 is the static "Undefined". So this is 95
// real names of a 328-entry space, recovered by decoding the initialiser's
// `mov [table + 80*i], offset "..."` stores; it is not a partial read of a
// complete table.
//
// GENERATED by work/gen_action_names.py -- do not edit.

#include <cstdint>

namespace creature {

enum : uint32_t { kNumCreatureActions = 328 };

// The action's name, or nullptr where the binary assigns none.
const char* GetCreatureActionName(uint32_t action);

// How many of the 328 carry a name.
uint32_t CountNamedCreatureActions();

// Where an action dispatches to.
//
// The +52 slot in each action record is NOT the implementing function, which is
// what it looked like at first. It is a compiler-generated vcall thunk --
// `mov eax,[ecx] ; jmp [eax+N]` -- so the record holds a pointer-to-member and
// sub_4B6CA0's call is the MSVC PMF sequence: adjust `this` by the record's
// delta, then tail-call a virtual slot. The useful part is therefore the slot,
// not the thunk address.
//
// 52 of the 95 named actions dispatch this way, across 32 distinct slots --
// variants share an implementation (245 and 246 both reach slot 194).
//
// Returns the vtable slot index, or -1 if the action has no dispatch entry.
int32_t GetCreatureActionVTableSlot(uint32_t action);

// The thunk's own address in the v1.0 binary, or 0. Kept for provenance so the
// decode can be re-checked against the image.
uint32_t GetCreatureActionThunkAddress(uint32_t action);

}  // namespace creature
