#pragma once
// GENERATED by work/gen_chooser_dispatch.py -- do not edit.
// Which slots of the chooser's two runtime dispatch tables the v1.0 binary
// fills (see the script for addresses and the reading functions).
#include <cstdint>

namespace creature {

enum : uint8_t {
    kActHasValidity = 1,  // action +16
    kActHasFit      = 2,  // action +52
    kActNeedsObject = 4,  // action +68
};
enum : uint8_t {
    kDesHasGate        = 1,  // desire +0
    kDesHasTargetedFit = 2,  // desire +16
    kDesHasBeliefFit   = 4,  // desire +20
    kDesHasSpecial     = 8,  // desire +36
};

inline constexpr uint8_t kActionDispatch[328] = {
    0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 2, 2, 2, 6, 6, 0, 1, 2, 2,
    2, 3, 1, 0, 5, 0, 0, 0, 6, 3, 6, 6, 6, 6, 6, 6, 6, 2, 2, 3,
    3, 3, 2, 2, 0, 1, 1, 1, 3, 3, 0, 3, 2, 1, 1, 0, 2, 2, 1, 1,
    2, 3, 2, 2, 2, 2, 2, 0, 6, 6, 1, 0, 0, 4, 0, 1, 0, 0, 3, 2,
    0, 1, 0, 5, 2, 0, 0, 0, 1, 1, 0, 2, 0, 2, 2, 1, 1, 1, 1, 1,
    1, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
    3, 1, 0, 0, 0, 3, 3, 3, 3, 3, 2, 3, 2, 2, 0, 6, 3, 3, 3, 2,
    2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 2, 2,
    0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 4, 0, 2, 0, 1, 0, 0, 1, 0,
    0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 2, 0, 1, 1, 1, 0, 1, 2, 3, 3,
    3, 2, 3, 3, 3, 0, 0, 1, 2, 2, 2, 2, 2, 0, 2, 2, 1, 0, 1, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 3, 1, 4, 4, 6, 4, 2, 2, 3, 3,
    1, 6, 0, 0, 0, 6, 3, 6, 3, 4, 2, 0, 4, 2, 2, 0, 2, 2, 2, 3,
    2, 2, 6, 2, 2, 3, 2, 0, 0, 2, 2, 2, 2, 3, 3, 0, 2, 2, 0, 2,
    6, 6, 3, 6, 0, 6, 3, 2, 2, 2, 2, 4, 0, 2, 3, 3, 2, 3, 2, 2,
    3, 2, 3, 6, 3, 3, 6, 6, 6, 2, 2, 2, 2, 1, 0, 2, 0, 2, 0, 1,
    2, 0, 2, 2, 2, 3, 5, 5,
};

inline constexpr uint8_t kDesireDispatch[40] = {
    6, 6, 6, 12, 0, 4, 12, 4, 4, 0, 1, 0, 0, 4, 0, 0, 6, 1, 0, 1,
    1, 0, 1, 5, 0, 0, 2, 0, 0, 0, 0, 6, 6, 1, 4, 1, 0, 6, 0, 0,
};

}  // namespace creature
