#pragma once
// CreatureActionNames — the creature actions that carry a name in the binary.
//
// A creature's plan names a CREATURE_ACTION, of which there are 328
// (NUM_CREATURE_ACTIONS). Each has an 80-byte record in a runtime dispatch
// table at 0x8FFCB8: the name at +0, a handler function pointer at +32, and a
// second code pointer at +52. sub_4B6CA0 dispatches through it.
//
// The table is .bss, filled by a long inlined initialiser around 0x481000, and
// only entries 233..327 have their name slot written -- indices 1..232 are
// never assigned at all, and index 0 is the static "Undefined". So this is 95
// real names of a 328-entry space, recovered by decoding the initialiser's
// `mov [table + 80*i], offset "..."` stores; it is not a partial read of a
// complete table.
//
// GENERATED by work/gen_action_names.py -- do not edit.

#include <cstdint>

namespace creature {

enum : uint32_t { kNumCreatureActions = 328 };

// The action's name, or nullptr where the binary assigns none.
const char* GetCreatureActionName(uint32_t action);

// How many of the 328 carry a name.
uint32_t CountNamedCreatureActions();

}  // namespace creature
