// GENERATED by work/gen_chooser_dispatch.py -- do not edit.
#include <black/CreatureDispatch.gen.h>
#include <black/GameThingWithPos.h>

namespace creature {

bool CallObjectPredicate(GameThingWithPos* obj, Creature* creature, int slot) {
    if (!obj) return false;
    switch (slot) {
    case 12: return obj->IsCreature(creature) != 0;
    case 112: return obj->IsActivityObjectWhichAngerAppliesTo(creature) != 0;
    case 113: return obj->IsActivityObjectWhichCompassionAppliesTo(creature) != 0;
    case 115: return obj->IsTownBelongingToAnotherPlayer(creature) != 0;
    case 123: return obj->IsRock_1(creature) != 0;
    case 138: return obj->CanBeHealedByCreature(creature) != 0;
    case 139: return obj->CanBeEatenByCreature(creature) != 0;
    case 140: return obj->CanCreatureEatMe(creature) != 0;
    case 141: return obj->CanBeAttackedByCreature(creature) != 0;
    case 142: return obj->CanBeFrighteningToCreature(creature) != 0;
    case 143: return obj->CanBeHelpedByCreature(creature) != 0;
    case 144: return obj->CanBePlayedWithByCreature(creature) != 0;
    case 145: return obj->CanBeImpressedByCreature(creature) != 0;
    case 146: return obj->CanBeInspectedByCreature(creature) != 0;
    case 147: return obj->CanBePoodUponByCreature(creature) != 0;
    case 148: return obj->CanBeBefriendedByCreature(creature) != 0;
    case 149: return obj->CanBeSleptNextToByCreature(creature) != 0;
    case 150: return obj->CanBePickedUpByCreature(creature) != 0;
    case 151: return obj->CanBeStrokedByCreature(creature) != 0;
    case 154: return obj->CanBeStompedOnByCreature(creature) != 0;
    case 158: return obj->CanBeDestroyedByStoning(creature) != 0;
    case 159: return obj->CanBeStonedAndEatenByCreature(creature) != 0;
    case 160: return obj->CanBeExaminedByCreature(creature) != 0;
    case 161: return obj->CanBeFoughtByCreature(creature) != 0;
    case 163: return obj->CanActAsAContainer(creature) != 0;
    case 164: return obj->IsBeingBuilt(creature) != 0;
    case 165: return obj->NeedsRepair(creature) != 0;
    case 166: return obj->IsOnFire(creature) != 0;
    case 167: return obj->IsNotOnFire(creature) != 0;
    case 169: return obj->IsMushroom(creature) != 0;
    case 175: return obj->CanHaveMagicFoodCastOnMe(creature) != 0;
    case 176: return obj->CanHaveMagicWoodCastOnMe(creature) != 0;
    case 178: return obj->IsVillager(creature) != 0;
    case 179: return obj->IsVillagerFarFromHome(creature) != 0;
    case 180: return obj->IsVillagerInTownWithoutManyBreeders(creature) != 0;
    case 182: return obj->IsVillagerBelongingToOtherPlayer(creature) != 0;
    case 184: return obj->CanBePoodOn(creature) != 0;
    case 186: return obj->IsVillagerWhoHasNotBeenDancedWithRecently(creature) != 0;
    case 188: return obj->DoesTotemBelongToATownWhichIsVeryImpressedIndeed(creature) != 0;
    case 189: return obj->IsDominantCreature(creature) != 0;
    case 192: return obj->IsStoragePit(creature) != 0;
    case 194: return obj->IsWorshipSite_0(creature) != 0;
    case 197: return obj->IsWorkshop_1(creature) != 0;
    case 198: return obj->IsBuildingWhichIsBeingBuilt(creature) != 0;
    case 199: return obj->IsStoragePitWithFoodInIt(creature) != 0;
    case 200: return obj->IsFieldWhichNeedsWatering(creature) != 0;
    case 201: return obj->IsFieldWithFoodInIt(creature) != 0;
    case 204: return obj->IsStoragePitBelongingToMyPlayer(creature) != 0;
    case 205: return obj->BenefitsFromHavingWaterSprinkledOnIt(creature) != 0;
    case 207: return obj->IsTree_0(creature) != 0;
    case 209: return obj->IsTreeBigEnoughForCreature(creature) != 0;
    case 210: return obj->IsAFoodPileOutsideStoragePit(creature) != 0;
    case 212: return obj->IsDoingSomethingInteresting(creature) != 0;
    case 214: return obj->IsPickupableRock(creature) != 0;
    case 216: return obj->IsCitadelPart_1(creature) != 0;
    case 217: return obj->IsPlayingFootball(creature) != 0;
    case 218: return obj->IsPlayingFootballAndMySideHasJustScored(creature) != 0;
    case 219: return obj->IsPlayingFootballAndOtherSideHasJustScored(creature) != 0;
    case 220: return obj->CanBeBroughtHomeByCreature(creature) != 0;
    case 221: return obj->IsAnimalBelongingToOtherPlayer(creature) != 0;
    case 222: return obj->IsOneOffSpellBelongingToOtherPlayer(creature) != 0;
    case 227: return obj->CanBeKickedByCreature(creature) != 0;
    case 229: return obj->IsStealableByCreature(creature) != 0;
    case 231: return obj->IsStealableScaffold(creature) != 0;
    case 233: return obj->IsTotemWithStealableSpell(creature) != 0;
    case 234: return obj->IsCreatureAvailableForJointActivity(creature) != 0;
    case 235: return obj->IsCreatureNotAvailableForJointActivity(creature) != 0;
    case 236: return obj->IsToyAwayFromHome(creature) != 0;
    case 238: return obj->IsToyBall(creature) != 0;
    case 239: return obj->IsToyDie(creature) != 0;
    case 240: return obj->IsToyCuddly(creature) != 0;
    case 242: return obj->IsLiving_0(creature) != 0;
    case 245: return obj->NothingScareyNearMe() != 0;
    case 247: return obj->IsCreatureWhoSeemsFriendly(creature) != 0;
    case 248: return obj->CanBeThrownInTheSeaPlayfully(creature) != 0;
    default: return false;
    }
}

}  // namespace creature
