// GENERATED by work/gen_action_names.py -- do not edit.
//
// Names and handler addresses decoded from the dispatch-table initialiser.
// The handler address is where that action is implemented in
// runblack_decrypted.exe (v1.0) -- recorded so the next pass can jump
// straight to the code for an action instead of hunting for it.

#include "black/CreatureActionNames.h"

namespace creature {

namespace {

struct Entry { uint32_t action; const char* name; uint32_t handler; };

const Entry kNames[] = {
    { 233, "PickUpAndCastOneOffSpellCompassionate", 0x0 },
    { 234, "PickUpAndCastOneOffSpellPlayful", 0x0 },
    { 235, "PickUpAndCastOneOffSpellToRestoreHealth", 0x0 },
    { 236, "Kick", 0x4ab4f0 },
    { 237, "Catch", 0x4ab730 },
    { 238, "PutOutFireWithMagicWater", 0x4ab6f0 },
    { 239, "SprinkleMagicWaterOnCrops", 0x4ab640 },
    { 240, "CastMagicWater", 0x0 },
    { 241, "PlayThrowingGameWithFriend", 0x0 },
    { 242, "NoticeHelpfulAction", 0x0 },
    { 243, "NoticeAggressiveAction", 0x0 },
    { 244, "NoticeAction", 0x0 },
    { 245, "PutFoodByWorshipSite", 0x4ab410 },
    { 246, "CastMagicFoodByWorshipSite", 0x4ab410 },
    { 247, "GiveWoodFromTreeToBuildingSite", 0x4ab6e0 },
    { 248, "CastMagicWoodByBuildingSite", 0x4ab6e0 },
    { 249, "PlantTree", 0x0 },
    { 250, "DanceOutsideWorshipSite", 0x4ab410 },
    { 251, "DanceAroundArtefact", 0x0 },
    { 252, "ThrowToImpress", 0x0 },
    { 253, "StealSpell", 0x4ab380 },
    { 254, "StealScaffolding", 0x4ab270 },
    { 255, "CatchFireballAndThrowBack", 0x0 },
    { 256, "TellCreatureToSodOff", 0x0 },
    { 257, "OrderFriendAround", 0x0 },
    { 258, "TakeFoodFromFieldToHome", 0x4ab3d0 },
    { 259, "TakeFishHome", 0x0 },
    { 260, "WaveAtFriend", 0x0 },
    { 261, "DeadForever", 0x0 },
    { 262, "GiveWoodFromTreeToWorkshop", 0x4ab630 },
    { 263, "ThrowAround", 0x4ab400 },
    { 264, "StealAndPutInTown", 0x4ab620 },
    { 265, "StealAndPutByCitadel", 0x4ab620 },
    { 266, "BreakRock", 0x4ab6d0 },
    { 267, "NoticeStealingAction", 0x0 },
    { 268, "NoticePlayfulAction", 0x0 },
    { 269, "EatFromFieldWithFriend", 0x0 },
    { 270, "GetFriendToGiveMeFoodFromField", 0x0 },
    { 271, "EatFishWithFriend", 0x0 },
    { 272, "GetFriendToGiveMeFish", 0x0 },
    { 273, "AttackWithFriend", 0x0 },
    { 274, "HelpTownWithFriend", 0x0 },
    { 275, "ExamineObjectInHand", 0x0 },
    { 276, "EatObjectInHand", 0x4ab520 },
    { 277, "StrokeObjectInHand", 0x4ab400 },
    { 278, "ThrowObjectInHand", 0x0 },
    { 279, "GetAttentionFromFriend", 0x4ab4d0 },
    { 280, "ExamineOtherCreatureWithFriend", 0x0 },
    { 281, "GiveFriendToy", 0x0 },
    { 282, "Sacrifice", 0x4ab400 },
    { 283, "SetFireToObject", 0x4ab260 },
    { 284, "WatchPlayer", 0x0 },
    { 285, "DropCowInStoragePit", 0x4ab350 },
    { 286, "CastShieldAroundTown", 0x4ab350 },
    { 287, "MakeBreederDisciple", 0x4ab580 },
    { 288, "PlayGameWithVillagers", 0x4ab470 },
    { 289, "TakeVillagerHomeToSleep", 0x4ab4c0 },
    { 290, "KickBallAround", 0x4ab6c0 },
    { 291, "ThrowBallAtObject", 0x0 },
    { 292, "DanceOnYourOwnByTheSea", 0x0 },
    { 293, "DancePlayfullyWithVillagersWatching", 0x4ab470 },
    { 294, "DancePlayfullyWithVillagersParticipating", 0x4ab460 },
    { 295, "TellVillagersAStory", 0x4ab460 },
    { 296, "PlayfullyFrightenVillagers", 0x4ab470 },
    { 297, "CastAmusingSpellOnCreature", 0x4ab240 },
    { 298, "KickTree", 0x4ab2c0 },
    { 299, "PlayfullyInteractWithVillager", 0x4ab470 },
    { 300, "PutFishByWorshipSite", 0x4ab410 },
    { 301, "PlayfullyKissVillager", 0x4ab470 },
    { 302, "CastMagicWoodByWorkShop", 0x4ab630 },
    { 303, "BringVillagerToWorshipSite", 0x4ab410 },
    { 304, "WaterTree", 0x4ab2c0 },
    { 305, "WaterField", 0x4ab2f0 },
    { 306, "StealFoodFromFarm", 0x4ab570 },
    { 307, "StealFoodFromStoragePit", 0x4ab570 },
    { 308, "StealWoodFromStoragePit", 0x4ab570 },
    { 309, "DanceAmorouslyWithVillagers", 0x4ab470 },
    { 310, "StealSpellSeed", 0x4ab6b0 },
    { 311, "StealAnimal", 0x4ab600 },
    { 312, "StealVillager", 0x4ab6a0 },
    { 313, "SleepOnTheSpot", 0x0 },
    { 314, "LookAtCameraInWideScreen", 0x0 },
    { 315, "HowlAtFriend", 0x0 },
    { 316, "HowlAtPlayer", 0x0 },
    { 317, "TellFriendAJoke", 0x0 },
    { 318, "PrayToPlayer", 0x0 },
    { 319, "PrayAtCitadel", 0x0 },
    { 320, "TalkToFriend", 0x0 },
    { 321, "PointOutHighlight", 0x0 },
    { 322, "TakeToyHome", 0x4ab560 },
    { 323, "StrokeToy", 0x4ab2e0 },
    { 324, "ThrowDie", 0x4ab230 },
    { 325, "SprinkleMagicWaterPU1OnCrops", 0x4ab640 },
    { 326, "WaterTreeForTown", 0x0 },
    { 327, "WaterTree", 0x0 },
};

}  // namespace

const char* GetCreatureActionName(uint32_t action) {
    for (const Entry& e : kNames)
        if (e.action == action) return e.name;
    return nullptr;
}

uint32_t GetCreatureActionHandlerAddress(uint32_t action) {
    for (const Entry& e : kNames)
        if (e.action == action) return e.handler;
    return 0;
}

uint32_t CountNamedCreatureActions() {
    return sizeof(kNames) / sizeof(kNames[0]);
}

}  // namespace creature
