// GENERATED by work/gen_action_names.py -- do not edit.
//
// Names and dispatch targets decoded from the action table's initialiser.

#include "black/CreatureActionNames.h"

namespace creature {

namespace {

struct Entry { uint32_t action; const char* name; uint32_t thunk; int32_t vslot; };

const Entry kNames[] = {
    { 233, "PickUpAndCastOneOffSpellCompassionate",  0x000000,   -1 },
    { 234, "PickUpAndCastOneOffSpellPlayful",        0x000000,   -1 },
    { 235, "PickUpAndCastOneOffSpellToRestoreHealth", 0x000000,   -1 },
    { 236, "Kick",                                   0x4ab4f0,  227 },
    { 237, "Catch",                                  0x4ab730,  150 },
    { 238, "PutOutFireWithMagicWater",               0x4ab6f0,  166 },
    { 239, "SprinkleMagicWaterOnCrops",              0x4ab640,  205 },
    { 240, "CastMagicWater",                         0x000000,   -1 },
    { 241, "PlayThrowingGameWithFriend",             0x000000,   -1 },
    { 242, "NoticeHelpfulAction",                    0x000000,   -1 },
    { 243, "NoticeAggressiveAction",                 0x000000,   -1 },
    { 244, "NoticeAction",                           0x000000,   -1 },
    { 245, "PutFoodByWorshipSite",                   0x4ab410,  194 },
    { 246, "CastMagicFoodByWorshipSite",             0x4ab410,  194 },
    { 247, "GiveWoodFromTreeToBuildingSite",         0x4ab6e0,  198 },
    { 248, "CastMagicWoodByBuildingSite",            0x4ab6e0,  198 },
    { 249, "PlantTree",                              0x000000,   -1 },
    { 250, "DanceOutsideWorshipSite",                0x4ab410,  194 },
    { 251, "DanceAroundArtefact",                    0x000000,   -1 },
    { 252, "ThrowToImpress",                         0x000000,   -1 },
    { 253, "StealSpell",                             0x4ab380,  233 },
    { 254, "StealScaffolding",                       0x4ab270,  231 },
    { 255, "CatchFireballAndThrowBack",              0x000000,   -1 },
    { 256, "TellCreatureToSodOff",                   0x000000,   -1 },
    { 257, "OrderFriendAround",                      0x000000,   -1 },
    { 258, "TakeFoodFromFieldToHome",                0x4ab3d0,  201 },
    { 259, "TakeFishHome",                           0x000000,   -1 },
    { 260, "WaveAtFriend",                           0x000000,   -1 },
    { 261, "DeadForever",                            0x000000,   -1 },
    { 262, "GiveWoodFromTreeToWorkshop",             0x4ab630,  197 },
    { 263, "ThrowAround",                            0x4ab400,  242 },
    { 264, "StealAndPutInTown",                      0x4ab620,  229 },
    { 265, "StealAndPutByCitadel",                   0x4ab620,  229 },
    { 266, "BreakRock",                              0x4ab6d0,  214 },
    { 267, "NoticeStealingAction",                   0x000000,   -1 },
    { 268, "NoticePlayfulAction",                    0x000000,   -1 },
    { 269, "EatFromFieldWithFriend",                 0x000000,   -1 },
    { 270, "GetFriendToGiveMeFoodFromField",         0x000000,   -1 },
    { 271, "EatFishWithFriend",                      0x000000,   -1 },
    { 272, "GetFriendToGiveMeFish",                  0x000000,   -1 },
    { 273, "AttackWithFriend",                       0x000000,   -1 },
    { 274, "HelpTownWithFriend",                     0x000000,   -1 },
    { 275, "ExamineObjectInHand",                    0x000000,   -1 },
    { 276, "EatObjectInHand",                        0x4ab520,  139 },
    { 277, "StrokeObjectInHand",                     0x4ab400,  242 },
    { 278, "ThrowObjectInHand",                      0x000000,   -1 },
    { 279, "GetAttentionFromFriend",                 0x4ab4d0,  235 },
    { 280, "ExamineOtherCreatureWithFriend",         0x000000,   -1 },
    { 281, "GiveFriendToy",                          0x000000,   -1 },
    { 282, "Sacrifice",                              0x4ab400,  242 },
    { 283, "SetFireToObject",                        0x4ab260,  167 },
    { 284, "WatchPlayer",                            0x000000,   -1 },
    { 285, "DropCowInStoragePit",                    0x4ab350,  192 },
    { 286, "CastShieldAroundTown",                   0x4ab350,  192 },
    { 287, "MakeBreederDisciple",                    0x4ab580,  180 },
    { 288, "PlayGameWithVillagers",                  0x4ab470,  178 },
    { 289, "TakeVillagerHomeToSleep",                0x4ab4c0,  179 },
    { 290, "KickBallAround",                         0x4ab6c0,  238 },
    { 291, "ThrowBallAtObject",                      0x000000,   -1 },
    { 292, "DanceOnYourOwnByTheSea",                 0x000000,   -1 },
    { 293, "DancePlayfullyWithVillagersWatching",    0x4ab470,  178 },
    { 294, "DancePlayfullyWithVillagersParticipating", 0x4ab460,  186 },
    { 295, "TellVillagersAStory",                    0x4ab460,  186 },
    { 296, "PlayfullyFrightenVillagers",             0x4ab470,  178 },
    { 297, "CastAmusingSpellOnCreature",             0x4ab240,  247 },
    { 298, "KickTree",                               0x4ab2c0,  207 },
    { 299, "PlayfullyInteractWithVillager",          0x4ab470,  178 },
    { 300, "PutFishByWorshipSite",                   0x4ab410,  194 },
    { 301, "PlayfullyKissVillager",                  0x4ab470,  178 },
    { 302, "CastMagicWoodByWorkShop",                0x4ab630,  197 },
    { 303, "BringVillagerToWorshipSite",             0x4ab410,  194 },
    { 304, "WaterTree",                              0x4ab2c0,  207 },
    { 305, "WaterField",                             0x4ab2f0,  200 },
    { 306, "StealFoodFromFarm",                      0x4ab570,  204 },
    { 307, "StealFoodFromStoragePit",                0x4ab570,  204 },
    { 308, "StealWoodFromStoragePit",                0x4ab570,  204 },
    { 309, "DanceAmorouslyWithVillagers",            0x4ab470,  178 },
    { 310, "StealSpellSeed",                         0x4ab6b0,  222 },
    { 311, "StealAnimal",                            0x4ab600,  221 },
    { 312, "StealVillager",                          0x4ab6a0,  182 },
    { 313, "SleepOnTheSpot",                         0x000000,   -1 },
    { 314, "LookAtCameraInWideScreen",               0x000000,   -1 },
    { 315, "HowlAtFriend",                           0x000000,   -1 },
    { 316, "HowlAtPlayer",                           0x000000,   -1 },
    { 317, "TellFriendAJoke",                        0x000000,   -1 },
    { 318, "PrayToPlayer",                           0x000000,   -1 },
    { 319, "PrayAtCitadel",                          0x000000,   -1 },
    { 320, "TalkToFriend",                           0x000000,   -1 },
    { 321, "PointOutHighlight",                      0x000000,   -1 },
    { 322, "TakeToyHome",                            0x4ab560,  236 },
    { 323, "StrokeToy",                              0x4ab2e0,  240 },
    { 324, "ThrowDie",                               0x4ab230,  239 },
    { 325, "SprinkleMagicWaterPU1OnCrops",           0x4ab640,  205 },
    { 326, "WaterTreeForTown",                       0x000000,   -1 },
    { 327, "WaterTree",                              0x000000,   -1 },
};

}  // namespace

const char* GetCreatureActionName(uint32_t action) {
    for (const Entry& e : kNames)
        if (e.action == action) return e.name;
    return nullptr;
}

int32_t GetCreatureActionVTableSlot(uint32_t action) {
    for (const Entry& e : kNames)
        if (e.action == action) return e.vslot;
    return -1;
}

uint32_t GetCreatureActionThunkAddress(uint32_t action) {
    for (const Entry& e : kNames)
        if (e.action == action) return e.thunk;
    return 0;
}

uint32_t CountNamedCreatureActions() {
    return sizeof(kNames) / sizeof(kNames[0]);
}

}  // namespace creature
