// GENERATED by work/gen_saveload.py -- do not edit by hand.
//
// Field tables recovered from runblack_decrypted.exe (v1.0) vtable slots
// 58 (Load) / 59 (Save) / 60 (GetSaveType) via tools/decomp/bw_decomp.py.
// Each row is one class's own contribution to the save stream, applied
// after its parent's -- the order the original code delegates in.
//
// 152 rows (98 usable), 908 fields, 178 save-type ids (122 fully exact).

#include "black/SaveLoadTable.h"

namespace saveload {

const Field kFields[] = {
    {    72,     4, OP_PTR },
    {   124,     1, OP_RAW },
    {   128,    12, OP_RAW },
    {   148,     4, OP_RAW },
    {   152,     4, OP_PTR },
    {   164,     4, OP_RAW },
    {   180,     1, OP_RAW },
    {   182,     1, OP_RAW },
    {   183,     1, OP_RAW },
    {   184,     1, OP_RAW },
    {   188,     4, OP_RAW },
    {   224,     4, OP_PTR },
    {   228,     2, OP_RAW },
    {   232,     2, OP_RAW },
    {   234,     2, OP_RAW },
    {   236,     2, OP_RAW },
    {   244,     8, OP_RAW },
    {   252,     4, OP_PTR },
    {   256,     4, OP_RAW },
    {   260,     4, OP_RAW },
    {   264,     4, OP_RAW },
    {   268,     1, OP_RAW },
    {   272,    48, OP_RAW },
    {   328,    48, OP_RAW },
    {   328,    12, OP_RAW },
    {   340,    16, OP_RAW },
    {   356,     4, OP_RAW },
    {   360,    48, OP_RAW },
    {   408,     4, OP_PTR },
    {    88,     4, OP_PTR },
    {    96,     4, OP_RAW },
    {   100,     4, OP_RAW },
    {   108,     4, OP_RAW },
    {    20,     4, OP_PTR },
    {    24,     4, OP_PTR },
    {    36,     4, OP_PTR },
    {    40,     4, OP_RAW },
    {    44,     4, OP_PTR },
    {    56,     4, OP_PTR },
    {    48,     4, OP_RAW },
    {    52,     4, OP_RAW },
    {    20,     4, OP_RAW },
    {    24,     4, OP_PTR },
    {    28,     4, OP_RAW },
    {    32,     4, OP_RAW },
    {    36,     4, OP_RAW },
    {    40,     4, OP_RAW },
    {    44,    12, OP_RAW },
    {   108,    12, OP_RAW },
    {   120,    12, OP_RAW },
    {   148,     4, OP_PTR },
    {   152,     4, OP_PTR },
    {   156,     4, OP_PTR },
    {   160,     4, OP_PTR },
    {   164,    12, OP_RAW },
    {   176,     4, OP_RAW },
    {   128,     4, OP_PTR },
    {   132,     4, OP_RAW },
    {   148,     4, OP_RAW },
    {    20,     4, OP_PTR },
    {    28,     4, OP_RAW },
    {     4,     4, OP_PTR },
    {    36,     4, OP_RAW },
    {     4,     4, OP_PTR },
    {    44,     4, OP_RAW },
    {     4,     4, OP_PTR },
    {    48,     4, OP_RAW },
    {    52,  1536, OP_RAW },
    {  1588,     4, OP_RAW },
    {  1592,     4, OP_RAW },
    {  1596,     4, OP_RAW },
    {  1600,     4, OP_RAW },
    {  1604,     6, OP_PTRARRAY },
    {  1604,     4, OP_PTR },
    {    92,    12, OP_RAW },
    {   104,     4, OP_RAW },
    {   108,     4, OP_RAW },
    {   112,     4, OP_RAW },
    {   116,     4, OP_RAW },
    {   128,     8, OP_RAW },
    {   136,   144, OP_RAW },
    {   280,   144, OP_RAW },
    {   424,    48, OP_RAW },
    {   120,     1, OP_RAW },
    {    48,     4, OP_PTR },
    {    52,     6, OP_PTRARRAY },
    {    80,     4, OP_RAW },
    {    96,     4, OP_RAW },
    {   104,     4, OP_RAW },
    {   108,     4, OP_RAW },
    {   112,     4, OP_RAW },
    {   116,     4, OP_RAW },
    {   124,     4, OP_RAW },
    {   128,     4, OP_PTR },
    {   136,     4, OP_PTR },
    {    40,     4, OP_INFO },
    {    44,     4, OP_PTR },
    {   240,     4, OP_RAW },
    {   244,     4, OP_RAW },
    {   248,     4, OP_RAW },
    {   252,     4, OP_PTR },
    {   256,     4, OP_RAW },
    {   260,     4, OP_RAW },
    {   264,     4, OP_RAW },
    {   268,     4, OP_RAW },
    {   272,     4, OP_RAW },
    {   276,     4, OP_RAW },
    {   280,    16, OP_RAW },
    {   296,     4, OP_RAW },
    {   232,     4, OP_PTR },
    {    20,     4, OP_PTR },
    {    24,     4, OP_PTR },
    {    32,     4, OP_RAW },
    {     4,     4, OP_PTR },
    {    36,     4, OP_RAW },
    {    60,     4, OP_RAW },
    {    64,     4, OP_RAW },
    {    68,     4, OP_RAW },
    {    72,     8, OP_RAW },
    {    80,     4, OP_RAW },
    {    84,     4, OP_RAW },
    {    88,     4, OP_RAW },
    {    92,    16, OP_RAW },
    {   108,     4, OP_RAW },
    {   112,     4, OP_PTR },
    {   116,     1, OP_RAW },
    {   120,     4, OP_RAW },
    {   124,     4, OP_RAW },
    {   128,     4, OP_RAW },
    {   132,     4, OP_RAW },
    {   136,    12, OP_RAW },
    {   148,    12, OP_RAW },
    {   160,     4, OP_RAW },
    {   164,     4, OP_RAW },
    {   168,    64, OP_RAW },
    {   232,    12, OP_RAW },
    {   376,     4, OP_RAW },
    {    24,     4, OP_RAW },
    {    28,     4, OP_RAW },
    {    32,    56, OP_RAW },
    {    20,     4, OP_RAW },
    {    28,     4, OP_RAW },
    {     4,     4, OP_PTR },
    {    32,     4, OP_RAW },
    {   148,     4, OP_INFO },
    {   156,     4, OP_RAW },
    {   288,     4, OP_INFO },
    {   200,     4, OP_RAW },
    {   220,     4, OP_RAW },
    {   280,     4, OP_PTR },
    {   284,     4, OP_RAW },
    {   204,     1, OP_RAW },
    {   208,     4, OP_RAW },
    {   216,     4, OP_RAW },
    {     4,     4, OP_PTR },
    {   224,     1, OP_RAW },
    {    92,     4, OP_RAW },
    {    96,    12, OP_RAW },
    {   108,    12, OP_RAW },
    {   120,    12, OP_RAW },
    {   132,    12, OP_RAW },
    {   144,     4, OP_RAW },
    {   148,     4, OP_RAW },
    {   152,     4, OP_RAW },
    {   156,     4, OP_RAW },
    {   160,     4, OP_RAW },
    {   164,     4, OP_RAW },
    {   168,     4, OP_RAW },
    {   172,     4, OP_RAW },
    {   176,     4, OP_RAW },
    {   180,     4, OP_RAW },
    {   184,     4, OP_RAW },
    {   188,     4, OP_RAW },
    {   192,     1, OP_RAW },
    {   132,     4, OP_RAW },
    {     4,     4, OP_PTR },
    {   140,     4, OP_PTR },
    {   144,     4, OP_RAW },
    {   148,     4, OP_RAW },
    {    84,     4, OP_PTR },
    {    88,     1, OP_RAW },
    {    92,     4, OP_RAW },
    {   100,     4, OP_PTR },
    {   116,     4, OP_PTR },
    {    48,     4, OP_PTR },
    {    52,     4, OP_PTR },
    {    56,     4, OP_PTR },
    {     8,     4, OP_PTR },
    {   136,     4, OP_RAW },
    {    76,     4, OP_RAW },
    {    80,     2, OP_RAW },
    {    82,     2, OP_RAW },
    {    84,     4, OP_RAW },
    {    88,     4, OP_RAW },
    {    92,     4, OP_RAW },
    {    96,    12, OP_RAW },
    {   108,    12, OP_RAW },
    {   120,     4, OP_RAW },
    {   124,     4, OP_RAW },
    {   128,     4, OP_RAW },
    {   132,     4, OP_PTR },
    {   140,     4, OP_RAW },
    {   196,     4, OP_PTR },
    {   200,    10, OP_PTRARRAY },
    {   240,    20, OP_PTRARRAY },
    {   320,     4, OP_PTR },
    {   332,    12, OP_RAW },
    {   476,     4, OP_RAW },
    {   480,     4, OP_RAW },
    {   484,     1, OP_RAW },
    {   488,     4, OP_RAW },
    {   492,     1, OP_RAW },
    {   496,     4, OP_RAW },
    {   500,     1, OP_RAW },
    {   504,     4, OP_RAW },
    {   508,     4, OP_RAW },
    {   512,     4, OP_RAW },
    {   516,     4, OP_RAW },
    {   520,     4, OP_RAW },
    {   524,     4, OP_RAW },
    {   528,     1, OP_RAW },
    {   529,     1, OP_RAW },
    {   532,     4, OP_RAW },
    {   536,     4, OP_RAW },
    {   540,     4, OP_PTR },
    {   576,     2, OP_PTRARRAY },
    {   584,     2, OP_PTRARRAY },
    {   592,     4, OP_PTR },
    {   600,    40, OP_PTRARRAY },
    {   776,    12, OP_RAW },
    {   596,     4, OP_PTR },
    {    24,     4, OP_RAW },
    {    32,     4, OP_RAW },
    {    24,     4, OP_RAW },
    {     4,     4, OP_PTR },
    {    24,    12, OP_RAW },
    {    20,     1, OP_RAW },
    {    44,     4, OP_RAW },
    {     4,     4, OP_PTR },
    { 409780,     4, OP_PTR },
    { 409784,     4, OP_PTR },
    { 409788,     4, OP_PTR },
    { 409792,     4, OP_PTR },
    { 409796,     4, OP_PTR },
    {    60,     4, OP_RAW },
    {    48,     4, OP_PTR },
    {    64,     4, OP_RAW },
    {    76,     4, OP_RAW },
    {    84,     4, OP_RAW },
    {    56,     4, OP_PTR },
    {     0,     4, OP_CHECKSUM },
    {     4,     4, OP_RAW },
    {    10,     1, OP_RAW },
    {    20,    12, OP_RAW },
    {    36,     2, OP_RAW },
    {    40,     4, OP_RAW },
    {    44,     4, OP_RAW },
    {    48,     4, OP_RAW },
    {    52,     4, OP_RAW },
    {    60,     4, OP_RAW },
    {    64,     4, OP_RAW },
    {    68,     4, OP_RAW },
    {    72,     4, OP_RAW },
    {   116,     4, OP_RAW },
    {   144,     4, OP_RAW },
    {   148,     1, OP_RAW },
    {   152,     4, OP_RAW },
    {   156,     4, OP_RAW },
    {   160,     4, OP_RAW },
    {   172,     4, OP_RAW },
    {   176,     4, OP_RAW },
    {   180,     4, OP_RAW },
    {   184,     4, OP_RAW },
    {   188,     4, OP_RAW },
    {   192,     4, OP_RAW },
    {   196,     4, OP_RAW },
    {    52,     4, OP_PTR },
    {    56,     4, OP_RAW },
    {    60,     4, OP_RAW },
    {   924,     4, OP_PTR },
    {    40,     1, OP_RAW },
    {    64,     4, OP_RAW },
    {    68,    48, OP_RAW },
    {   144,     1, OP_RAW },
    {   148,     8, OP_RAW },
    {   156,     4, OP_RAW },
    {   160,     4, OP_RAW },
    {   164,    12, OP_RAW },
    {   176,    12, OP_RAW },
    {   188,    12, OP_RAW },
    {   200,    12, OP_RAW },
    {   232,    12, OP_RAW },
    {   256,     4, OP_RAW },
    {   260,     4, OP_RAW },
    {   264,     4, OP_RAW },
    {   268,    12, OP_RAW },
    {   280,     4, OP_RAW },
    {   284,     4, OP_RAW },
    {    44,     4, OP_PTR },
    {   300,     4, OP_PTR },
    {    52,     4, OP_RAW },
    {    56,     4, OP_RAW },
    {    20,     4, OP_RAW },
    {    24,     4, OP_RAW },
    {    28,     4, OP_RAW },
    {    48,     1, OP_RAW },
    {    32,     4, OP_RAW },
    {    36,     4, OP_PTR },
    {    40,     4, OP_RAW },
    {    44,     4, OP_RAW },
    {    56,     4, OP_PTR },
    {    52,     4, OP_RAW },
    {    24,     4, OP_RAW },
    {    28,     4, OP_RAW },
    {    32,     4, OP_RAW },
    {    36,     4, OP_RAW },
    {    40,     4, OP_RAW },
    {    44,     4, OP_RAW },
    {    20,     4, OP_PTR },
    {    24,    12, OP_RAW },
    {    36,     4, OP_RAW },
    {    40,     8, OP_RAW },
    {    48,     4, OP_RAW },
    {    52,     4, OP_RAW },
    {    56,     4, OP_RAW },
    {    60,     4, OP_RAW },
    {    68,     4, OP_RAW },
    {    64,     4, OP_PTR },
    {   188,     4, OP_PTR },
    {    20,     1, OP_RAW },
    {    24,     1, OP_PTRARRAY },
    {   148,     4, OP_PTR },
    {   156,     4, OP_PTR },
    {   160,     4, OP_PTR },
    {   108,     4, OP_RAW },
    {   112,     4, OP_RAW },
    {   212,    12, OP_RAW },
    {   224,     4, OP_RAW },
    {   228,     4, OP_RAW },
    {   232,     4, OP_RAW },
    {   196,     4, OP_RAW },
    {   236,     4, OP_PTR },
    {   152,     4, OP_PTR },
    {   240,     4, OP_RAW },
    {   236,     4, OP_PTR },
    {   240,     4, OP_PTR },
    {   252,    12, OP_RAW },
    {   264,     4, OP_RAW },
    {   268,     4, OP_RAW },
    {   248,     4, OP_PTR },
    {   280,     4, OP_RAW },
    {   304,     4, OP_RAW },
    {     4,     4, OP_PTR },
    {   244,     4, OP_PTR },
    {    28,    12, OP_RAW },
    {    40,    48, OP_RAW },
    {    20,     4, OP_PTR },
    {    24,     1, OP_RAW },
    {    88,     1, OP_RAW },
    {    92,     4, OP_PTR },
    {   180,     4, OP_PTR },
    {    44,     4, OP_RAW },
    {    48,     4, OP_RAW },
    {    52,     4, OP_RAW },
    {    84,     2, OP_RAW },
    {    88,     4, OP_PTR },
    {    92,     4, OP_RAW },
    {    96,     4, OP_RAW },
    {   100,     4, OP_PTR },
    {   124,     4, OP_PTR },
    {   128,     4, OP_RAW },
    {   132,     4, OP_RAW },
    {    56,     1, OP_RAW },
    {    40,     4, OP_PTR },
    {    44,     4, OP_PTR },
    {    48,     4, OP_RAW },
    {    52,     4, OP_RAW },
    {    40,     4, OP_RAW },
    {    44,     4, OP_RAW },
    {    48,     4, OP_RAW },
    {    52,     4, OP_RAW },
    {    60,     4, OP_RAW },
    {    56,     4, OP_PTR },
    {    64,     4, OP_INFO },
    {   108,     4, OP_PTR },
    {    44,     4, OP_RAW },
    {     4,     4, OP_PTR },
    {    48,     4, OP_RAW },
    {    52,     4, OP_RAW },
    {    56,     4, OP_RAW },
    {    60,     4, OP_RAW },
    {    64,     4, OP_RAW },
    {    68,     4, OP_RAW },
    {    72,     4, OP_RAW },
    {    76,     4, OP_RAW },
    {    80,    12, OP_RAW },
    {    92,    12, OP_RAW },
    {   104,     4, OP_RAW },
    {   116,     4, OP_PTR },
    {   120,     4, OP_RAW },
    {   124,    12, OP_RAW },
    {    20,     4, OP_RAW },
    {    28,     4, OP_RAW },
    {     4,     4, OP_PTR },
    {    20,     4, OP_RAW },
    {    24,     4, OP_PTR },
    {    92,     4, OP_RAW },
    {    28,     1, OP_RAW },
    {    96,     4, OP_PTR },
    {   100,     4, OP_RAW },
    {   104,    12, OP_RAW },
    {    40,     4, OP_PTR },
    {    52,     4, OP_PTR },
    {    60,     4, OP_RAW },
    {     4,     4, OP_PTR },
    {    68,     4, OP_RAW },
    {     4,     4, OP_PTR },
    {    84,     4, OP_RAW },
    {    88,     4, OP_RAW },
    {    92,     4, OP_RAW },
    {    96,     4, OP_RAW },
    {   100,     4, OP_RAW },
    {   104,    42, OP_RAWARRAY },
    {   272,     4, OP_RAW },
    {   440,     4, OP_RAW },
    {   444,     4, OP_RAW },
    {   448,     4, OP_RAW },
    {   464,     1, OP_RAW },
    {   472,     8, OP_PTRARRAY },
    {    20,     4, OP_RAW },
    {    20,     1, OP_RAW },
    {   280,     4, OP_PTR },
    {   284,     4, OP_PTR },
    {   288,     4, OP_RAW },
    {    20,     4, OP_PTR },
    {    24,     4, OP_RAW },
    {   104,     4, OP_RAW },
    {   108,     4, OP_PTR },
    {   112,     4, OP_RAW },
    {   116,     1, OP_RAW },
    {   120,     4, OP_PTR },
    {   124,     4, OP_PTR },
    {   128,     1, OP_RAW },
    {   184,     4, OP_PTR },
    {   132,    48, OP_RAW },
    {    92,     4, OP_PTR },
    {    88,     1, OP_RAW },
    {    20,     4, OP_PTR },
    {    20,     4, OP_RAW },
    {    24,     4, OP_PTR },
    {    32,     4, OP_RAW },
    {    36,    60, OP_RAW },
    {    96,    12, OP_RAW },
    {   108,     1, OP_RAW },
    {   112,     4, OP_RAW },
    {   116,     4, OP_RAW },
    {   120,    12, OP_RAW },
    {   132,    12, OP_RAW },
    {   144,    12, OP_RAW },
    {   156,     4, OP_RAW },
    {   160,     4, OP_RAW },
    {   164,     4, OP_RAW },
    {   168,     4, OP_PTR },
    {   172,     1, OP_RAW },
    {   173,     1, OP_RAW },
    {    52,    12, OP_RAW },
    {    64,     4, OP_RAW },
    {    68,    48, OP_RAW },
    {   116,     4, OP_RAW },
    {   120,     4, OP_RAW },
    {   124,     4, OP_RAW },
    {   128,    12, OP_RAW },
    {   140,     4, OP_RAW },
    {   144,     4, OP_RAW },
    {   148,     2, OP_RAW },
    {   152,    56, OP_RAW },
    {   208,    56, OP_RAW },
    {   264,     4, OP_RAW },
    {   268,     4, OP_RAW },
    {   272,    12, OP_RAW },
    {   284,     4, OP_RAW },
    {   288,     4, OP_PTR },
    {   292,     4, OP_PTR },
    {   296,     4, OP_PTR },
    {   300,     1, OP_RAW },
    {    20,     2, OP_RAW },
    {    24,     4, OP_RAW },
    {    28,    12, OP_RAW },
    {    32,    12, OP_RAW },
    {    44,    12, OP_RAW },
    {    56,     4, OP_RAW },
    {    60,     4, OP_RAW },
    {    20,     1, OP_RAW },
    {    24,     4, OP_PTR },
    {    28,     4, OP_RAW },
    {    32,     4, OP_RAW },
    {    36,     4, OP_RAW },
    {    24,     4, OP_RAW },
    {    28,     4, OP_RAW },
    {    32,     4, OP_RAW },
    {    36,     4, OP_RAW },
    {    40,     4, OP_RAW },
    {    44,     4, OP_RAW },
    {    48,     4, OP_RAW },
    {    52,     4, OP_RAW },
    {    56,     1, OP_RAW },
    {    60,     4, OP_RAW },
    {    76,     4, OP_RAW },
    {    64,     1, OP_RAW },
    {    68,    28, OP_RAW },
    {    20,    12, OP_RAW },
    {    32,    12, OP_RAW },
    {    44,    12, OP_RAW },
    {    44,    12, OP_RAW },
    {    56,    12, OP_RAW },
    {    68,     4, OP_RAW },
    {    72,     4, OP_RAW },
    {    76,     1, OP_RAW },
    {    32,     4, OP_PTR },
    {    36,     4, OP_PTR },
    {    48,    12, OP_RAW },
    {    60,    12, OP_RAW },
    {    72,    12, OP_RAW },
    {    84,     4, OP_RAW },
    {    88,     1, OP_RAW },
    {    89,     1, OP_RAW },
    {    90,     1, OP_RAW },
    {    92,     4, OP_RAW },
    {    96,     4, OP_RAW },
    {   100,     4, OP_RAW },
    {   104,     4, OP_RAW },
    {   136,     4, OP_RAW },
    {   160,     4, OP_RAW },
    {   164,     4, OP_PTR },
    {   168,     4, OP_PTR },
    {   172,     4, OP_RAW },
    {   176,     4, OP_RAW },
    {   180,    12, OP_RAW },
    {    20,     4, OP_RAW },
    {    24,    12, OP_RAW },
    {    36,    12, OP_RAW },
    {    48,     4, OP_RAW },
    {    28,     4, OP_PTR },
    {    32,    16, OP_RAW },
    {    28,    24, OP_RAW },
    {    52,     4, OP_RAW },
    {    56,     4, OP_PTR },
    {    60,     1, OP_RAW },
    {    72,     4, OP_RAW },
    {  1404,     4, OP_RAW },
    {  1412,     4, OP_RAW },
    {  1408,     4, OP_RAW },
    {   972,     4, OP_RAW },
    {   920,     6, OP_PTRARRAY },
    {   196,     4, OP_PTRARRAY },
    {   212,     4, OP_PTRARRAY },
    {  1104,     4, OP_RAW },
    {  1172,    20, OP_PTRARRAY },
    {  1168,     4, OP_RAW },
    {   904,     4, OP_RAW },
    {   908,     2, OP_RAW },
    {   912,     4, OP_RAW },
    {   916,     4, OP_RAW },
    {   996,     4, OP_RAW },
    {  1000,     4, OP_RAW },
    {  1004,     4, OP_RAW },
    {  1008,     4, OP_RAW },
    {  1012,     4, OP_PTR },
    {  1016,     4, OP_PTR },
    {  1020,     4, OP_PTR },
    {   900,     4, OP_PTR },
    {    60,     4, OP_RAW },
    {    68,     2, OP_RAW },
    {    70,     2, OP_RAW },
    {   228,     4, OP_RAW },
    {   232,     4, OP_RAW },
    {   104,    12, OP_RAW },
    {   116,     4, OP_PTR },
    {   120,     4, OP_PTR },
    {   124,     4, OP_PTR },
    {   188,     4, OP_RAW },
    {   104,     4, OP_RAW },
    {    20,     4, OP_PTR },
    {    28,     4, OP_RAW },
    {    32,     4, OP_RAW },
    {    36,     4, OP_RAW },
    {    40,     4, OP_PTR },
    {    44,     4, OP_RAW },
    {    48,     4, OP_RAW },
    {    56,     4, OP_PTR },
    {    60,     4, OP_RAW },
    {   104,     4, OP_PTR },
    {   108,     4, OP_PTR },
    {   116,     4, OP_PTR },
    {   120,     4, OP_RAW },
    {   124,     4, OP_RAW },
    {   128,     4, OP_RAW },
    {   132,     4, OP_RAW },
    {   136,     4, OP_RAW },
    {   140,     4, OP_RAW },
    {   144,     4, OP_RAW },
    {   152,     4, OP_RAW },
    {   156,     4, OP_RAW },
    {   164,     4, OP_RAW },
    {   136,     4, OP_RAW },
    {   140,     4, OP_RAW },
    {   144,     4, OP_PTR },
    {   104,     4, OP_PTR },
    {   108,     4, OP_PTR },
    {   112,     4, OP_PTR },
    {   120,     4, OP_RAW },
    {   124,     4, OP_PTR },
    {   128,     4, OP_RAW },
    {   132,     4, OP_RAW },
    {   136,     2, OP_RAW },
    {   140,     4, OP_PTR },
    {   144,     4, OP_RAW },
    {    92,     4, OP_RAW },
    {    96,     4, OP_RAW },
    {   124,     4, OP_RAW },
    {   128,     4, OP_RAW },
    {   120,     4, OP_RAW },
    {   132,     4, OP_RAW },
    {    40,     4, OP_RAW },
    {    44,     4, OP_RAW },
    {    20,     4, OP_PTR },
    {    24,     3, OP_PTRARRAY },
    {    84,     4, OP_RAW },
    {    88,     4, OP_RAW },
    {    96,     4, OP_PTR },
    {    92,     4, OP_RAW },
    {   296,     4, OP_RAW },
    {   240,     4, OP_RAW },
    {     4,     4, OP_PTR },
    {   176,     4, OP_PTR },
    {    40,     4, OP_PTR },
    {    44,    12, OP_RAW },
    {   204,    12, OP_RAW },
    {   216,    12, OP_RAW },
    {    56,     4, OP_RAW },
    {    60,     4, OP_RAW },
    {    64,     4, OP_RAW },
    {    68,     4, OP_RAW },
    {    72,     4, OP_RAW },
    {    76,     4, OP_RAW },
    {   100,    60, OP_RAW },
    {    80,     4, OP_RAW },
    {    92,     1, OP_RAW },
    {    93,     1, OP_RAW },
    {   160,     4, OP_PTR },
    {   164,     4, OP_PTR },
    {   168,     4, OP_PTR },
    {   172,     4, OP_PTR },
    {   180,     4, OP_RAW },
    {   184,     4, OP_RAW },
    {   188,     4, OP_RAW },
    {   228,     4, OP_RAW },
    {   192,    12, OP_RAW },
    {    84,     4, OP_RAW },
    {    88,     4, OP_RAW },
    {   236,     4, OP_PTR },
    {   240,     1, OP_RAW },
    {   204,     4, OP_PTR },
    {   196,     4, OP_RAW },
    {   200,     4, OP_RAW },
    {   208,     4, OP_RAW },
    {   212,     4, OP_RAW },
    {   244,     4, OP_PTR },
    {   248,     4, OP_RAW },
    {   252,     4, OP_RAW },
    {   256,    12, OP_RAW },
    {   268,     4, OP_RAW },
    {   276,     4, OP_RAW },
    {   280,     4, OP_RAW },
    {   284,     1, OP_RAW },
    {   236,     1, OP_RAW },
    {   236,     4, OP_RAW },
    {   240,     1, OP_RAW },
    {   236,     4, OP_PTR },
    {   244,     4, OP_RAW },
    {   128,     4, OP_INFO },
    {   256,    12, OP_RAW },
    {   268,     4, OP_RAW },
    {   112,     1, OP_RAW },
    {    88,     4, OP_RAW },
    {   100,    12, OP_RAW },
    {    92,     1, OP_RAW },
    {    72,     4, OP_RAW },
    {    76,     4, OP_PTR },
    {    84,     4, OP_RAW },
    {    96,     4, OP_RAW },
    {   108,     4, OP_RAW },
    {    84,     1, OP_RAW },
    {    88,     4, OP_INFO },
    {    92,     4, OP_PTR },
    {   104,     4, OP_PTR },
    {    96,     4, OP_PTR },
    {   100,     4, OP_PTR },
    {   112,     1, OP_RAW },
    {   113,     1, OP_RAW },
    {   116,     4, OP_RAW },
    {   120,     4, OP_RAW },
    {   124,     4, OP_RAW },
    {   132,     4, OP_RAW },
    {   128,     4, OP_RAW },
    {   140,     4, OP_RAW },
    {   136,     4, OP_RAW },
    {   144,     1, OP_RAW },
    {   148,     4, OP_RAW },
    {   152,     4, OP_RAW },
    {   114,     1, OP_RAW },
    {   120,     4, OP_RAW },
    {   104,     4, OP_RAW },
    {   108,     4, OP_RAW },
    {   264,     4, OP_RAW },
    {     4,     4, OP_PTR },
    {   244,     4, OP_PTR },
    {   248,     4, OP_PTR },
    {    96,     4, OP_PTR },
    {   100,     4, OP_INFO },
    {   104,     4, OP_RAW },
    {   108,     4, OP_RAW },
    {   116,    52, OP_RAW },
    {   168,    52, OP_RAW },
    {   220,     4, OP_RAW },
    {   224,     4, OP_RAW },
    {   228,     4, OP_RAW },
    {   232,     4, OP_RAW },
    {   236,     4, OP_RAW },
    {   240,     4, OP_RAW },
    {   248,     1, OP_RAW },
    {   112,     1, OP_RAW },
    {   252,     4, OP_RAW },
    {   244,     4, OP_PTR },
    {    52,     4, OP_RAW },
    {    48,     1, OP_RAW },
    {    20,     4, OP_RAW },
    {    24,     4, OP_RAW },
    {    28,     4, OP_PTR },
    {    36,     4, OP_PTR },
    {    32,     4, OP_PTR },
    {    40,     4, OP_PTR },
    {    56,     1, OP_RAW },
    {    64,     4, OP_PTR },
    {    68,     4, OP_PTR },
    {    76,     4, OP_RAW },
    {     4,     4, OP_PTR },
    {   196,     1, OP_PTRARRAY },
    {   200,     5, OP_PTRARRAY },
    {    24,     4, OP_RAW },
    {    28,     4, OP_RAW },
    {    32,     4, OP_RAW },
    {    88,     4, OP_RAW },
    {   196,    12, OP_RAW },
    {   208,    12, OP_RAW },
    {   124,     4, OP_PTR },
    {   128,     4, OP_RAW },
    {   132,     4, OP_RAW },
    {   136,     4, OP_RAW },
    {    48,     4, OP_PTR },
    {  1432,    24, OP_RAW },
    {  1460,     4, OP_RAW },
    {  1464,     4, OP_RAW },
    {  1468,     1, OP_RAW },
    {  1472,     4, OP_RAW },
    {  1476,     4, OP_RAW },
    {  1480,     4, OP_RAW },
    {  1484,     4, OP_RAW },
    {  1488,     4, OP_RAW },
    {  1492,     4, OP_RAW },
    {  1496,     4, OP_RAW },
    {  1504,     4, OP_RAW },
    {  1508,     4, OP_RAW },
    {  1512,     4, OP_RAW },
    {  1516,     4, OP_RAW },
    {  1520,     4, OP_RAW },
    {  1524,     4, OP_RAW },
    {  1528,     2, OP_PTRARRAY },
    {  1540,     4, OP_RAW },
    {     4,     4, OP_PTR },
    {  1824,    12, OP_RAW },
    {  1836,    12, OP_RAW },
    {  1852,     4, OP_PTR },
    {  1856,     4, OP_PTR },
    {  1936,   464, OP_RAW },
    {  2416,     4, OP_PTR },
    {  2436,     4, OP_PTR },
    {  2460,     4, OP_PTR },
    {  2540,  1024, OP_RAW },
    {  3572,   168, OP_RAW },
    {  3740,     4, OP_PTR },
    {  3748,     4, OP_PTR },
    {  3752,     4, OP_RAW },
    {  3756,     4, OP_RAW },
    {  3760,     4, OP_RAW },
    {  3764,     4, OP_RAW },
    {  3768,     4, OP_RAW },
    {  3772,     4, OP_RAW },
    {  2472,    17, OP_PTRARRAY },
    {  1500,     4, OP_RAW },
    {  3864,     4, OP_RAW },
    {  1544,   280, OP_RAW },
    {   204,     4, OP_PTR },
    {   208,     6, OP_PTRARRAY },
    {   100,     4, OP_PTR },
    {    84,     4, OP_RAW },
    {    88,     4, OP_RAW },
    {    92,     4, OP_RAW },
    {    96,     4, OP_RAW },
    {   276,     4, OP_PTR },
    {   280,     4, OP_PTR },
    {   284,     4, OP_RAW },
    {    96,     2, OP_RAW },
    {   100,     4, OP_RAW },
    {   104,     4, OP_PTR },
    {    92,     2, OP_RAW },
    {   224,     2, OP_RAW },
    {   232,     4, OP_RAW },
    {   236,     4, OP_RAW },
    {   240,     1, OP_RAW },
    {   241,     1, OP_RAW },
    {   242,     1, OP_RAW },
    {   244,     2, OP_RAW },
    {   246,     2, OP_RAW },
    {   248,     2, OP_RAW },
    {   288,     4, OP_PTR },
    {   292,     4, OP_PTR },
    {   256,     4, OP_PTR },
    {    40,     4, OP_PTR },
    {    44,     4, OP_PTR },
    {   152,     4, OP_RAW },
    {   156,     4, OP_RAW },
    {   164,     4, OP_PTR },
    {    28,     1, OP_RAW },
    {    32,     4, OP_RAW },
    {    20,    12, OP_RAW },
    {    32,     4, OP_RAW },
    {    36,     4, OP_RAW },
    {    40,     4, OP_RAW },
    {    44,     4, OP_INFO },
    {    52,    16, OP_RAW },
    {    68,     8, OP_RAW },
    {    76,    12, OP_RAW },
    {    88,     4, OP_RAW },
    {   100,     1, OP_RAW },
    {   104,     4, OP_RAW },
    {   108,     4, OP_RAW },
    {   112,     4, OP_RAW },
    {   116,     4, OP_RAW },
    {   120,     4, OP_RAW },
    {   124,     4, OP_RAW },
    {   128,     4, OP_RAW },
    {   132,     1, OP_RAW },
    {    40,    80, OP_RAW },
    {     8,    12, OP_RAW },
    {   124,     4, OP_RAW },
    {   196,     4, OP_RAW },
    {   208,     4, OP_PTR },
    {   212,     4, OP_PTR },
    {   196,     4, OP_RAW },
    {   200,     4, OP_RAW },
    {   220,     1, OP_RAW },
    {   228,     4, OP_RAW },
    {     4,     4, OP_PTR },
    {    76,     4, OP_RAW },
    {   140,     4, OP_INFO },
    {   144,     4, OP_PTR },
    {   160,     4, OP_PTR },
    {   168,     4, OP_RAW },
    {     4,     4, OP_PTR },
    {   180,     4, OP_PTR },
    {   188,     4, OP_RAW },
    {   192,     4, OP_RAW },
    {   196,     1, OP_RAW },
    {   200,     4, OP_RAW },
    {   204,     4, OP_RAW },
    {   208,     4, OP_RAW },
    {   216,     4, OP_RAW },
    {     4,     4, OP_PTR },
    {   228,     4, OP_RAW },
    {   232,     2, OP_RAWARRAY },
    {   240,     4, OP_RAW },
    {   244,     4, OP_RAW },
    {   248,     4, OP_RAW },
    {   252,     4, OP_RAW },
    {   256,     4, OP_RAW },
    {   260,     4, OP_RAW },
    {   264,     4, OP_RAW },
    {   268,     4, OP_RAW },
    {   272,     1, OP_RAW },
    {   273,     1, OP_RAW },
    {   220,     4, OP_PTR },
    {   276,     4, OP_RAW },
    {   184,     4, OP_PTR },
    {   280,     4, OP_RAW },
    {   284,     4, OP_RAW },
    {   276,     2, OP_RAW },
    {   280,     4, OP_PTR },
    {   284,     4, OP_RAW },
    {   312,     4, OP_RAW },
    {   316,     2, OP_RAW },
    {   288,     1, OP_RAW },
    {   292,     4, OP_RAW },
    {   296,     4, OP_PTR },
    {   308,     4, OP_RAW },
    {   304,     4, OP_RAW },
    {   140,     4, OP_RAW },
    {   256,     4, OP_PTR },
    { 0, 0, OP_RAW },  // sentinel, never referenced
};

const ClassDesc kClasses[] = {
    { "PlannedAbode", 64, 0, 1, HOOK_NONE, true },  // 0x403f00
    { "GWaterfall", -1, 1, 0, HOOK_NONE, true },  // 0x404e70
    { "Abode", 30, 1, 10, HOOK_NONE, false },  // 0x405070
    { "Cow", 45, 11, 12, HOOK_NONE, true },  // 0x4178f0
    { "Bat", 3, 23, 0, HOOK_NONE, true },  // 0x41a1e0
    { "SpellBat", 4, 23, 1, HOOK_NONE, true },  // 0x41ac00
    { "SpellWolf", 3, 24, 5, HOOK_NONE, true },  // 0x41c050
    { "ArenaSpellIcon", 29, 29, 4, HOOK_NONE, true },  // 0x41fc20
    { "TownArtifact", 38, 33, 8, HOOK_NONE, true },  // 0x420820
    { "ThingMusicInfo", 38, 41, 7, HOOK_NONE, true },  // 0x423900
    { "Ball", 59, 48, 8, HOOK_NONE, true },  // 0x42fb10
    { "BigForest", 30, 56, 2, HOOK_NONE, true },  // 0x432030
    { "Bonfire", 102, 58, 1, HOOK_NONE, true },  // 0x432390
    { "BuildingSite", 38, 59, 13, HOOK_NONE, false },  // 0x434ee0
    { "CitadelBuildingSite", 13, 72, 1, HOOK_NONE, false },  // 0x435c60
    { "StandardBuildingSite", 13, 73, 1, HOOK_NONE, true },  // 0x435ed0
    { "GCamera", 39, 74, 10, HOOK_NONE, false },  // 0x43ac50
    { "Citadel", 19, 84, 8, HOOK_NONE, false },  // 0x44f190
    { "CitadelPart", 30, 92, 3, HOOK_NONE, true },  // 0x454920
    { "0x4568d0", 39, 95, 2, HOOK_NONE, true },  // 0x4568d0
    { "Creed", 59, 97, 0, HOOK_NONE, true },  // 0x4e9c20
    { "Dance", 40, 97, 13, HOOK_NONE, true },  // 0x4ea860
    { "DanceGroup", 38, 110, 27, HOOK_NONE, false },  // 0x4eb810
    { "DanceKeyAction", 38, 137, 3, HOOK_NONE, false },  // 0x4ec3a0
    { "DanceKeyFrame", 38, 140, 4, HOOK_NONE, false },  // 0x4ecc90
    { "DeadTree", 102, 144, 2, HOOK_NONE, true },  // 0x4eeb50
    { "Field", 2, 146, 10, HOOK_NONE, false },  // 0x5003f0
    { "FireFly", 62, 156, 18, HOOK_NONE, false },  // 0x502080
    { "FishFarm", 30, 174, 5, HOOK_NONE, false },  // 0x5037c0
    { "0x504440", 62, 179, 1, HOOK_NONE, true },  // 0x504440
    { "Feature", 29, 180, 4, HOOK_NONE, true },  // 0x505420
    { "Flock", 19, 184, 18, HOOK_NONE, false },  // 0x5065b0
    { "Football", 2, 202, 29, HOOK_NONE, false },  // 0x508b30
    { "GFootpath", 38, 231, 2, HOOK_NONE, false },  // 0x50ac40
    { "GFootpathLink", 38, 233, 2, HOOK_NONE, false },  // 0x50b310
    { "GFootpathNode", 38, 235, 4, HOOK_NONE, false },  // 0x50d460
    { "GFootpathFinder", 38, 239, 5, HOOK_NONE, false },  // 0x50d820
    { "Forest", 19, 244, 6, HOOK_NONE, false },  // 0x50f010
    { "GameThing", -1, 250, 3, HOOK_NONE, true },  // 0x53e8e0
    { "WayPoint", 38, 253, 2, HOOK_NONE, true },  // 0x53ed70
    { "0x55ee10", 39, 255, 21, HOOK_NONE, false },  // 0x55ee10
    { "InfluenceRing", 39, 276, 3, HOOK_NONE, false },  // 0x58e6c0
    { "GInterface", 39, 279, 1, HOOK_NONE, true },  // 0x590db0
    { "GInterfaceStatus", 39, 280, 22, HOOK_NONE, true },  // 0x59ca10
    { "GLeashStatus", 38, 302, 10, HOOK_NONE, true },  // 0x5a6bd0
    { "0x5acf00", 61, 312, 0, HOOK_LIVING, true },  // 0x5acf00  Living: fields then a trailing linked-list dump
    { "DataPath", 38, 312, 6, HOOK_NONE, true },  // 0x5ad5f0
    { "DataForScriptRemind", 38, 318, 10, HOOK_NONE, true },  // 0x5adbd0
    { "MagicFood", 74, 328, 1, HOOK_NONE, true },  // 0x5b8450
    { "GMagicHand", -1, 329, 2, HOOK_NONE, false },  // 0x5b8b80
    { "MagicTeleport", 60, 331, 3, HOOK_NONE, true },  // 0x5b96e0
    { "MagicTree", 139, 334, 2, HOOK_NONE, true },  // 0x5ba730
    { "LandscapeVortexVolc", 60, 336, 5, HOOK_NONE, false },  // 0x5bd370
    { "LandscapeVortexIn", 52, 341, 3, HOOK_NONE, false },  // 0x5bd7d0
    { "LandscapeVortexOut", 52, 344, 10, HOOK_NONE, false },  // 0x5bd9a0
    { "VortexObjectInfo", 77, 354, 6, HOOK_NONE, false },  // 0x5bde40
    { "MagicWood", 75, 360, 1, HOOK_NONE, true },  // 0x5be230
    { "Mist", 39, 361, 3, HOOK_NONE, true },  // 0x5c1ec0
    { "0x5c2160", 62, 364, 1, HOOK_NONE, true },  // 0x5c2160
    { "Poo", 58, 365, 4, HOOK_NONE, true },  // 0x5c3040
    { "MobileStatic", 30, 369, 3, HOOK_NONE, true },  // 0x5c3520
    { "0x5c7040", 58, 372, 0, HOOK_MOBILE, true },  // 0x5c7040  MobileWallHug: fields with a hold-type dependent middle block
    { "GBaseOnly", 39, 372, 0, HOOK_OBJECT, true },  // 0x5ebe00  Object: fields then the conditional physics transform block
    { "GParticleContainer", 39, 372, 5, HOOK_NONE, true },  // 0x5efc90
    { "PlannedMultiMapFixed", 39, 377, 7, HOOK_NONE, true },  // 0x5f6b10
    { "PlayerActionState", 39, 384, 17, HOOK_NONE, false },  // 0x5fd700
    { "PlayerSubAction", 38, 401, 3, HOOK_NONE, false },  // 0x5fdce0
    { "PlayerSubActionArgument", 38, 404, 7, HOOK_NONE, false },  // 0x5fdee0
    { "GComputerPlayer", 39, 411, 18, HOOK_NONE, false },  // 0x602c20
    { "GComputerAttitudeToPlayer", 38, 429, 1, HOOK_NONE, true },  // 0x603c90
    { "GComputerPlayerQueue", 38, 430, 4, HOOK_NONE, false },  // 0x60f170
    { "GComputerSeen", 38, 434, 2, HOOK_NONE, true },  // 0x610440
    { "Pot", 59, 436, 4, HOOK_NONE, true },  // 0x617400
    { "0x617760", 72, 440, 3, HOOK_NONE, true },  // 0x617760
    { "PileFood", 75, 443, 1, HOOK_NONE, true },  // 0x619120
    { "PileWood", 73, 444, 1, HOOK_NONE, true },  // 0x6191a0
    { "MagicFireBall", 62, 445, 2, HOOK_NONE, true },  // 0x62bbc0
    { "0x66a560", 38, 447, 0, HOOK_NONE, true },  // 0x66a560
    { "GJPSysInterface", 77, 447, 1, HOOK_NONE, true },  // 0x66a580
    { "PSysManager", 77, 448, 17, HOOK_NONE, false },  // 0x66a5b0
    { "BaseAtomModifierData", 77, 465, 0, HOOK_NONE, false },  // 0x66a860
    { "AtomCore", 77, 465, 20, HOOK_NONE, false },  // 0x66a890
    { "DrawOffset", 77, 485, 1, HOOK_NONE, true },  // 0x66ada0
    { "DrawOffsetLT", 82, 486, 2, HOOK_NONE, true },  // 0x66ae00
    { "DrawOffsetDecay", 82, 488, 4, HOOK_NONE, true },  // 0x66aeb0
    { "RenderParticle", 77, 492, 1, HOOK_NONE, true },  // 0x66afc0
    { "Particle3DPnt", 85, 493, 0, HOOK_NONE, true },  // 0x66b020
    { "ParticleChainJoint", 85, 493, 4, HOOK_NONE, true },  // 0x66b9c0
    { "Chain", 77, 497, 13, HOOK_NONE, false },  // 0x66bc00
    { "UR_PlasmaInf", 77, 510, 8, HOOK_NONE, true },  // 0x66c1e0
    { "UR_Lightning_CollectionData", 80, 518, 20, HOOK_NONE, false },  // 0x66d280
    { "SpellPointInf", 77, 538, 4, HOOK_NONE, true },  // 0x66dac0
    { "DefensiveShield", 77, 542, 1, HOOK_NONE, true },  // 0x66ed50
    { "DefensiveSphere", 92, 543, 1, HOOK_NONE, true },  // 0x66ed80
    { "PSysSound", 38, 544, 4, HOOK_NONE, true },  // 0x66fab0
    { "PuzzleGame", 39, 548, 26, HOOK_NONE, false },  // 0x6779f0
    { "PuzzleTotem", 132, 574, 2, HOOK_NONE, true },  // 0x678b20
    { "HanoiBlock", 59, 576, 4, HOOK_NONE, true },  // 0x679ca0
    { "PuzzleGrain", 74, 580, 1, HOOK_NONE, true },  // 0x67a160
    { "PuzzleMobileObject", 59, 581, 1, HOOK_NONE, true },  // 0x67a230
    { "Reaction", 38, 582, 9, HOOK_NONE, false },  // 0x67fb50
    { "Reward", 59, 591, 13, HOOK_NONE, true },  // 0x681ac0
    { "Rock", 60, 604, 3, HOOK_NONE, true },  // 0x6825d0
    { "Scaffold", 59, 607, 10, HOOK_NONE, true },  // 0x684e20
    { "ScriptHighlight", 29, 617, 6, HOOK_NONE, true },  // 0x6a3f20
    { "ScriptTimer", 39, 623, 2, HOOK_NONE, true },  // 0x6aab10
    { "ShowNeeds", 38, 625, 2, HOOK_NONE, false },  // 0x6b14c0
    { "ShowNeedsVisuals", 62, 627, 4, HOOK_NONE, true },  // 0x6b1a00
    { "SpecialVillager", 140, 631, 1, HOOK_NONE, true },  // 0x6b6890
    { "SpellTeleport", 110, 632, 2, HOOK_NONE, false },  // 0x6b83d0
    { "Spell", 39, 634, 26, HOOK_NONE, true },  // 0x6b89f0
    { "SpellCreature", 110, 660, 2, HOOK_NONE, true },  // 0x6b9560
    { "SpellDispenser", 2, 662, 5, HOOK_NONE, true },  // 0x6b9cc0
    { "0x6bb750", 109, 667, 5, HOOK_NONE, true },  // 0x6bb750
    { "SpellFlockFlying", 113, 672, 3, HOOK_NONE, true },  // 0x6bb970
    { "SpellFlockGround", 113, 675, 0, HOOK_NONE, true },  // 0x6bba80
    { "SpellResource", 110, 675, 1, HOOK_NONE, true },  // 0x6bc1b0
    { "SpellWater", 110, 676, 1, HOOK_NONE, true },  // 0x6bc280
    { "SpellForest", 110, 677, 3, HOOK_NONE, true },  // 0x6bc970
    { "SpellIcon", 30, 680, 3, HOOK_NONE, true },  // 0x6be480
    { "SpellSeedGraphic", 39, 683, 8, HOOK_NONE, true },  // 0x6be7b0
    { "SpellSeed", 62, 691, 20, HOOK_NONE, true },  // 0x6c06e0
    { "OneOffSpellSeed", 59, 711, 3, HOOK_NONE, true },  // 0x6c1340
    { "SpellShield", 109, 714, 4, HOOK_NONE, false },  // 0x6c2500
    { "MapShield", 29, 718, 2, HOOK_NONE, true },  // 0x6c2b10
    { "MagicShield", 124, 720, 0, HOOK_NONE, true },  // 0x6c2b70
    { "PhysicalShield", 124, 720, 14, HOOK_NONE, true },  // 0x6c2e80
    { "FireEffect", 38, 734, 13, HOOK_NONE, false },  // 0x6c6db0
    { "StoragePit", 2, 747, 2, HOOK_NONE, false },  // 0x6c99c0
    { "GStream", 38, 749, 3, HOOK_NONE, false },  // 0x6ca1d0
    { "GStreetLantern", 62, 752, 1, HOOK_NONE, true },  // 0x6caa30
    { "GStreetLight", 39, 753, 0, HOOK_NONE, true },  // 0x6cad30
    { "Totem", 2, 753, 2, HOOK_NONE, true },  // 0x6cb7b0
    { "TotemStatue", 30, 755, 4, HOOK_NONE, true },  // 0x6cc500
    { "Town", 19, 759, 43, HOOK_NONE, false },  // 0x6d1980
    { "TownCentre", 2, 802, 2, HOOK_NONE, false },  // 0x6d66f0
    { "TownDesireFlags", 62, 804, 5, HOOK_NONE, true },  // 0x6d8a70
    { "TownSpellIcon", 119, 809, 1, HOOK_NONE, true },  // 0x6da890
    { "TownCentreSpellIcon", 137, 810, 2, HOOK_NONE, false },  // 0x6da910
    { "Tree", 29, 812, 4, HOOK_NONE, true },  // 0x6dd5d0
    { "Villager", 45, 816, 12, HOOK_NONE, false },  // 0x6e3d60
    { "MissionaryControl", 39, 828, 2, HOOK_NONE, true },  // 0x6e5f80
    { "Fragment", 102, 830, 3, HOOK_NONE, false },  // 0x6fd2f0
    { "VortexSave", 38, 833, 2, HOOK_NONE, false },  // 0x6fd7e0
    { "GClimate", 38, 835, 18, HOOK_NONE, false },  // 0x700410
    { "WeatherThing", 39, 853, 3, HOOK_NONE, false },  // 0x701550
    { "Wonder", 2, 856, 1, HOOK_NONE, true },  // 0x702450
    { "Workshop", 2, 857, 7, HOOK_NONE, false },  // 0x703150
    { "PlannedWorshipSite", 0, 864, 1, HOOK_NONE, true },  // 0x704ff0
    { "WorshipSite", 18, 865, 31, HOOK_NONE, false },  // 0x706000
    { "WorshipSpellIcon", 119, 896, 10, HOOK_NONE, false },  // 0x708440
    { "WorshipTotem", 18, 906, 2, HOOK_NONE, true },  // 0x709250
};
const uint16_t kClassCount = 152;

// save-type id -> kClasses index, ascending by id for binary search.
const SaveTypeRow kSaveTypes[] = {
    {    0,  80 },  // BaseAtomModifierData
    {    1,  33 },  // GFootpath
    {    2,  34 },  // GFootpathLink
    {    3,  35 },  // GFootpathNode
    {    5,  36 },  // GFootpathFinder
    {    6, 140 },  // Villager
    {    7,   2 },  // Abode
    {    8, 128 },  // StoragePit
    {    9, 110 },  // Spell
    {   10, 116 },  // SpellResource
    {   12, 117 },  // SpellWater
    {   13, 114 },  // SpellFlockFlying
    {   14, 115 },  // SpellFlockGround
    {   15, 118 },  // SpellForest
    {   16, 110 },  // SpellStormAndTornado
    {   17, 123 },  // SpellShield
    {   18, 110 },  // SpellHeal
    {   19, 111 },  // SpellCreature
    {   20, 109 },  // SpellWithObjects
    {   21, 109 },  // SpellTeleport
    {   22,  94 },  // PSysSound
    {   23, 126 },  // PhysicalShield
    {   24, 125 },  // MagicShield
    {   25,  50 },  // MagicTeleport
    {   26,  52 },  // LandscapeVortexVolc
    {   27,  53 },  // LandscapeVortexIn
    {   28,  54 },  // LandscapeVortexOut
    {   29,  51 },  // MagicTree
    {   30,  48 },  // MagicFood
    {   31,  56 },  // MagicWood
    {   32,  76 },  // MagicFireBall
    {   35, 120 },  // SpellSeedGraphic
    {   36, 121 },  // SpellSeed
    {   37, 122 },  // OneOffSpellSeed
    {   38, 100 },  // Reaction
    {   39,  21 },  // Dance
    {   40, 134 },  // Town
    {   41, 127 },  // FireEffect
    {   42,  27 },  // FireFly
    {   43, 132 },  // Totem
    {   44,  95 },  // PuzzleGame
    {   45,   3 },  // PuzzleCow
    {   46,   3 },  // PuzzleLion
    {   47,   3 },  // PuzzleVillager
    {   48,  97 },  // HanoiBlock
    {   49,  96 },  // PuzzleTotem
    {   50,  26 },  // Field
    {   53,  17 },  // Citadel
    {   54,  18 },  // CitadelPart
    {   55,   0 },  // PlannedCitadelPart
    {   56,  64 },  // PlannedMultiMapFixed
    {   57,   0 },  // PlannedTownCitadelHeart
    {   59, 148 },  // PlannedWorshipSite
    {   60, 149 },  // WorshipSite
    {   61, 107 },  // ShowNeedsVisuals
    {   62, 106 },  // ShowNeeds
    {   63, 104 },  // ScriptHighlight
    {   64,   1 },  // GWaterfall
    {   66,   7 },  // ArenaSpellIcon
    {   67, 145 },  // WeatherThing
    {   68,  10 },  // Ball
    {   69,  32 },  // Football
    {   70, 101 },  // Reward
    {   71, 129 },  // GStream
    {   72,  57 },  // Mist
    {   73,  41 },  // InfluenceRing
    {   76, 136 },  // TownDesireFlags
    {   77,  11 },  // BigForest
    {   78,  37 },  // Forest
    {   79, 139 },  // Tree
    {   80,   2 },  // Creche
    {   81, 146 },  // Graveyard
    {   82, 147 },  // Workshop
    {   83,  59 },  // MobileObject
    {   84,  60 },  // MobileStatic
    {   85, 137 },  // TownSpellIcon
    {   86, 138 },  // TownCentreSpellIcon
    {   88,  72 },  // Pot
    {   89,  74 },  // PileFood
    {   90,  75 },  // PileWood
    {   91,  28 },  // FishFarm
    {   92,  15 },  // StandardBuildingSite
    {   93,  14 },  // CitadelBuildingSite
    {   95, 103 },  // Scaffold
    {   96, 135 },  // TownCentre
    {   97,   0 },  // PlannedAbode
    {   98,   0 },  // PlannedTownCentre
    {  100,  42 },  // GInterface
    {  101,  43 },  // GInterfaceStatus
    {  102,  68 },  // GComputerPlayer
    {  103,  71 },  // GComputerSeen
    {  104,  71 },  // GComputerSpellCast
    {  107,  59 },  // Poo
    {  108,  59 },  // FieldCrop
    {  109,  20 },  // Creed
    {  110,  63 },  // GParticleContainer
    {  111, 102 },  // Rock
    {  112,  25 },  // DeadTree
    {  113,  25 },  // FelledTree
    {  114,  12 },  // Bonfire
    {  115,   0 },  // PlannedFeature
    {  116,  30 },  // Feature
    {  118, 108 },  // SpecialVillager
    {  119,  16 },  // GCamera
    {  120, 150 },  // WorshipSpellIcon
    {  121,  23 },  // DanceKeyAction
    {  122,  24 },  // DanceKeyFrame
    {  123,  22 },  // DanceGroup
    {  124, 131 },  // ScriptMarker
    {  125, 105 },  // ScriptTimer
    {  126,  31 },  // Flock
    {  127, 133 },  // TotemStatue
    {  128, 146 },  // Wonder
    {  129, 119 },  // SpellIcon
    {  130,   3 },  // Cow
    {  131,   3 },  // Sheep
    {  132,   3 },  // Goat
    {  134,   3 },  // Zebra
    {  135,   3 },  // Pig
    {  136,   3 },  // Tortoise
    {  137,   3 },  // Lion
    {  138,   3 },  // Leopard
    {  139,   3 },  // Tiger
    {  140,   3 },  // Wolf
    {  141,   6 },  // SpellWolf
    {  142,   4 },  // Dove
    {  143,   4 },  // Crow
    {  144,   5 },  // SpellDove
    {  145,   4 },  // Swallow
    {  146,   4 },  // Pigeon
    {  147,   4 },  // Seagull
    {  148,   4 },  // Bat
    {  149,   5 },  // SpellBat
    {  150,   4 },  // Vulture
    {  151,  20 },  // Whale
    {  152, 151 },  // WorshipTotem
    {  153,  46 },  // DataPath
    {  154,   3 },  // PieceLion
    {  155,   3 },  // Horse
    {  156,   3 },  // PieceWolf
    {  157,   3 },  // PieceVillager
    {  158, 141 },  // MissionaryControl
    {  161,  39 },  // WayPoint
    {  162,  81 },  // AtomCore
    {  164,  79 },  // PSysManager
    {  165,  78 },  // GJPSysInterface
    {  166,  83 },  // DrawOffsetLT
    {  167,  84 },  // DrawOffsetDecay
    {  168,  86 },  // Particle3DPnt
    {  179,  87 },  // ParticleChainJoint
    {  182,  88 },  // Chain
    {  183,  93 },  // DefensiveSphere
    {  184,  91 },  // SpellPointInf
    {  186,  89 },  // UR_PlasmaInf
    {  202,  55 },  // VortexObjectInfo
    {  216,  90 },  // UR_Lightning_CollectionData
    {  246,  62 },  // GBaseOnly
    {  247, 142 },  // Fragment
    {  248,   2 },  // Windmill
    {  249,  65 },  // PlayerActionState
    {  250,  66 },  // PlayerSubAction
    {  251,  67 },  // PlayerSubActionArgument
    {  252, 144 },  // GClimate
    {  253,  49 },  // GMagicHand
    {  254, 130 },  // GStreetLantern
    {  255, 131 },  // GStreetLight
    {  258,  44 },  // GLeashStatus
    {  259,   8 },  // TownArtifact
    {  261,  47 },  // DataForScriptRemind
    {  262, 143 },  // VortexSave
    {  263,  98 },  // PuzzleGrain
    {  264,  99 },  // PuzzleMobileObject
    {  265,   9 },  // ThingMusicInfo
    {  266,  30 },  // Flowers
    {  267, 112 },  // SpellDispenser
    {  268,  70 },  // GComputerPlayerQueue
    {  269,  69 },  // GComputerAttitudeToPlayer
    {  272,  62 },  // CitadelEntrance
};
const uint16_t kSaveTypeCount = 178;

}  // namespace saveload
