"""Generate the creature desire enums from chlasm (bw1-decomp, CC0).

Transcribing 78 enumerators by hand is a typo waiting to happen, and these are
load-bearing: the source enum is what proves a parsed mind file is being read
correctly (each desire's sources must be the ones named for it).
"""
import re

OUT = "src/include/black/CreatureDesireEnums.h"
SRC = {
    "CREATURE_DESIRES": "vendor/bw1-decomp/libs/chlasm/Enum.h",
    "CREATURE_DESIRE_SOURCE": "vendor/bw1-decomp/libs/chlasm/CreatureEnum.h",
}


def read_enum(name, path):
    out, inside = [], False
    for line in open(path, encoding="utf-8", errors="replace"):
        if re.match(r"\s*enum\s+%s\s*$" % name, line):
            inside = True
            continue
        if inside:
            if line.strip().startswith("}"):
                break
            m = re.match(r"\s*([A-Z_0-9]+)\s*=\s*(\d+)", line)
            if m:
                out.append((m.group(1), int(m.group(2))))
    return out


def main():
    parts = {k: read_enum(k, v) for k, v in SRC.items()}
    w = open(OUT, "w", newline="\n").write
    w("#pragma once\n"
      "// Creature desire enums -- GENERATED by work/gen_desire_enums.py from\n"
      "// vendor/bw1-decomp/libs/chlasm (CC0, public domain). Do not edit here.\n"
      "//\n"
      "// These name the indices in a CreatureMind file: the 40 desires in order,\n"
      "// and the source each desire draws from. Reading a shipped mind and finding\n"
      "// that desire 0's sources are exactly the IMPRESS_* ones is what proves the\n"
      "// file format was decoded correctly -- see CreatureMindFile.h.\n\n"
      "#include <cstdint>\n\n")
    for name, entries in parts.items():
        w("enum %s : uint32_t {\n" % name)
        for ident, val in entries:
            w("    %-52s = %d,\n" % (ident, val))
        w("};\n\n")
    w("// Name of a desire / source, or nullptr. Handy in debug output and in the\n"
      "// tests, where the whole point is checking one against the other.\n"
      "const char* GetCreatureDesireName(uint32_t desire);\n"
      "const char* GetCreatureDesireSourceName(uint32_t source);\n")
    print("wrote %s" % OUT)
    for k, v in parts.items():
        print("  %-28s %d entries" % (k, len(v)))


if __name__ == "__main__":
    main()
