"""Recover the creature chooser's two runtime dispatch tables by emulation.

Both tables are .bss, filled by straight-line static initialisers that IDA left
as data, and most of their stores go through registers -- so neither a
`mov [abs], imm` scan nor xrefs can read them. Running the initialiser under
unicorn and dumping the table afterwards does.

  action table  0x8FFCB8, 328 x 80 bytes, initialiser 0x479CA0
      +16 validity predicate (PMF)    sub_4D1BE0 / sub_4D0E30
      +52 target-fit predicate         sub_4C4D20
      +68 needs an object             sub_4D13B0 / sub_4D1A90
  desire table  0xBA8BB0,  40 x 40 bytes, initialiser 0x4BD770
      +0  gate predicate (PMF)        sub_4AC290 / sub_4AC390
      +16 targeted-desire fit         sub_4AC390
      +20 belief fit                  sub_4C4BD0; non-null lets sub_4AC290 offer it
      +36 special belief score        sub_4CA6A0

Writes src/include/black/CreatureDispatch.gen.h: one flag byte per entry saying
which slots the binary fills. The predicates themselves read world state, so
the host supplies them; where the binary has none the chooser does not ask.

    py -3.11 work/gen_chooser_dispatch.py <runblack_decrypted.exe>
"""
import struct
import sys

import pefile
from unicorn import Uc, UC_ARCH_X86, UC_MODE_32, UC_HOOK_CODE
from unicorn.x86_const import UC_X86_REG_EAX, UC_X86_REG_EIP, UC_X86_REG_ESP

exe = sys.argv[1] if len(sys.argv) > 1 else "game_data/runblack_decrypted.exe"
pe = pefile.PE(exe)
img = pe.get_memory_mapped_image()


def run(start, table, count, stride):
    mu = Uc(UC_ARCH_X86, UC_MODE_32)
    mu.mem_map(0x400000, max(0x900000, (len(img) + 0xFFF) & ~0xFFF))
    mu.mem_write(0x400000, img)
    mu.mem_map(0x100000, 0x10000)
    sentinel = 0x100800
    mu.reg_write(UC_X86_REG_ESP, 0x108000)
    mu.mem_write(0x108000, struct.pack("<I", sentinel))

    def hook(uc, addr, size, _):
        if addr == sentinel:
            uc.emu_stop()
        elif uc.mem_read(addr, 1)[0] == 0xE8:  # neither initialiser calls out; skip if one ever does
            uc.reg_write(UC_X86_REG_EIP, addr + size)
            uc.reg_write(UC_X86_REG_EAX, 0)

    mu.hook_add(UC_HOOK_CODE, hook)
    mu.emu_start(start, sentinel, count=2_000_000)
    return [struct.unpack(f"<{stride // 4}I", bytes(mu.mem_read(table + stride * i, stride)))
            for i in range(count)]


actions = run(0x479CA0, 0x8FFCB8, 328, 80)
desires = run(0x4BD770, 0xBA8BB0, 40, 40)

act = [(1 if r[4] else 0) | (2 if r[13] else 0) | (4 if r[17] else 0) for r in actions]
des = [(1 if r[0] else 0) | (2 if r[4] else 0) | (4 if r[5] else 0) | (8 if r[9] else 0) for r in desires]


def rows(v):
    return "\n".join("    " + ", ".join(str(x) for x in v[i:i + 20]) + "," for i in range(0, len(v), 20))


out = f"""#pragma once
// GENERATED by work/gen_chooser_dispatch.py -- do not edit.
// Which slots of the chooser's two runtime dispatch tables the v1.0 binary
// fills (see the script for addresses and the reading functions).
#include <cstdint>

namespace creature {{

enum : uint8_t {{
    kActHasValidity = 1,  // action +16
    kActHasFit      = 2,  // action +52
    kActNeedsObject = 4,  // action +68
}};
enum : uint8_t {{
    kDesHasGate        = 1,  // desire +0
    kDesHasTargetedFit = 2,  // desire +16
    kDesHasBeliefFit   = 4,  // desire +20
    kDesHasSpecial     = 8,  // desire +36
}};

inline constexpr uint8_t kActionDispatch[328] = {{
{rows(act)}
}};

inline constexpr uint8_t kDesireDispatch[40] = {{
{rows(des)}
}};

}}  // namespace creature
"""
open("src/include/black/CreatureDispatch.gen.h", "w", newline="\n").write(out)
print(f"actions: {sum(1 for a in act if a & 1)} validity, {sum(1 for a in act if a & 2)} fit, "
      f"{sum(1 for a in act if a & 4)} need an object; desires: {des}")
