"""Emit the C++ serialization table from work/decomp/save_table.json.

Writes  src/core/SaveLoadTable.gen.cpp   the table
        work/decomp/save_ids.txt         class -> save-type id

A row describes one class's own contribution to the save stream: the ordered
field writes its Save body performs after delegating to its parent. Rows are
keyed by the address of the binary's Save body, so classes that do not override
Save share a row exactly as they share the code.

Three rows in the binary are not a flat field list -- they branch or walk a
list -- and are marked with a hook instead; SaveLoad.cpp implements those by
hand and the generated field list for them is dropped so ordering stays
explicit. Rows that are neither flat nor hooked are marked inexact, and the
runtime refuses them rather than writing a stream that silently disagrees with
the original.
"""
import json

TABLE = "work/decomp/save_table.json"
OUT_CPP = "src/core/SaveLoadTable.gen.cpp"
OUT_IDS = "work/decomp/save_ids.txt"

OPS = {"raw": "OP_RAW", "ptr": "OP_PTR", "info": "OP_INFO",
       "ptrarray": "OP_PTRARRAY", "rawarray": "OP_RAWARRAY", "chk": "OP_CHECKSUM"}

# Save bodies that branch or walk a container: hand-written in SaveLoad.cpp.
HOOKS = {
    "0x5ebe00": ("HOOK_OBJECT", "Object: fields then the conditional physics transform block"),
    "0x5acf00": ("HOOK_LIVING", "Living: fields then a trailing linked-list dump"),
    "0x5c7040": ("HOOK_MOBILE", "MobileWallHug: fields with a hold-type dependent middle block"),
}


def main():
    d = json.load(open(TABLE))
    rows = d["rows"]
    ids = d["ids"]
    cls_save = d["cls_save"]

    by_addr = {r["addr"]: r for r in rows}
    order = sorted(by_addr)
    index = {a: i for i, a in enumerate(order)}

    def chain(addr):
        out, seen = [], set()
        while addr in by_addr and addr not in seen:
            seen.add(addr)
            out.append(addr)
            addr = by_addr[addr]["parent"]
        return out

    def exact(r):
        if r["addr"] in HOOKS:
            return True
        # Save and Load are mirror images in the original; if our two
        # independent parses disagree, one of them missed something.
        return not r["odd"] and r["save_ops"] == r["load_ops"]

    fields, descs = [], []
    for a in order:
        r = by_addr[a]
        hook = HOOKS.get(a, ("HOOK_NONE", ""))[0]
        own = [] if a in HOOKS else r["save_ops"]
        descs.append(dict(name=r["name"], addr=a,
                          parent=index.get(r["parent"], -1) if r["parent"] else -1,
                          first=len(fields), count=len(own),
                          hook=hook, exact=exact(r)))
        fields += own

    id_rows, complete, partial = {}, [], []
    for cls, tid in sorted(ids.items(), key=lambda kv: (kv[1], kv[0])):
        a = cls_save.get(cls)
        if a is None or a not in index:
            continue
        id_rows.setdefault(tid, (index[a], cls))
        (complete if all(exact(by_addr[x]) for x in chain(a)) else partial).append((tid, cls))

    with open(OUT_IDS, "w", newline="\n") as f:
        for cls, tid in sorted(ids.items()):
            f.write("%-32s %d\n" % (cls, tid))

    w = open(OUT_CPP, "w", newline="\n").write
    w("// GENERATED by work/gen_saveload.py -- do not edit by hand.\n"
      "//\n"
      "// Field tables recovered from runblack_decrypted.exe (v1.0) vtable slots\n"
      "// 58 (Load) / 59 (Save) / 60 (GetSaveType) via tools/decomp/bw_decomp.py.\n"
      "// Each row is one class's own contribution to the save stream, applied\n"
      "// after its parent's -- the order the original code delegates in.\n"
      "//\n"
      "// %d rows (%d usable), %d fields, %d save-type ids (%d fully exact).\n\n"
      % (len(descs), sum(1 for x in descs if x["exact"]), len(fields),
         len(id_rows), len(complete)))
    w('#include "black/SaveLoadTable.h"\n\nnamespace saveload {\n\n')

    w("const Field kFields[] = {\n")
    for kind, off, n in fields:
        w("    { %5d, %5d, %s },\n" % (off, n, OPS[kind]))
    w("    { 0, 0, OP_RAW },  // sentinel, never referenced\n};\n\n")

    w("const ClassDesc kClasses[] = {\n")
    for x in descs:
        note = HOOKS.get(x["addr"], (None, ""))[1]
        w('    { "%s", %d, %d, %d, %s, %s },  // %s%s\n'
          % (x["name"], x["parent"], x["first"], x["count"], x["hook"],
             "true" if x["exact"] else "false", x["addr"],
             "  " + note if note else ""))
    w("};\nconst uint16_t kClassCount = %d;\n\n" % len(descs))

    w("// save-type id -> kClasses index, ascending by id for binary search.\n")
    w("const SaveTypeRow kSaveTypes[] = {\n")
    for tid in sorted(id_rows):
        i, cls = id_rows[tid]
        w("    { %4d, %3d },  // %s\n" % (tid, i, cls))
    w("};\nconst uint16_t kSaveTypeCount = %d;\n\n" % len(id_rows))
    w("}  // namespace saveload\n")

    print("rows          : %d (%d usable)" % (len(descs), sum(1 for x in descs if x["exact"])))
    print("fields        :", len(fields))
    print("save-type ids : %d" % len(id_rows))
    print("  exact chain : %d" % len(complete))
    print("  partial     : %d" % len(partial))
    print("\nstill partial:")
    print("  " + " ".join(c for _, c in partial))


if __name__ == "__main__":
    main()
