# Emit src/include/black/InfoDatLayout.gen.h from work/decomp/info_layout.txt
# (written by info_layout.py). No IDA needed for this step.
import os
HERE = os.path.dirname(os.path.abspath(__file__))
rows = [l.split() for l in open(os.path.join(HERE, "decomp/info_layout.txt"))
        if l.strip() and not l.startswith("#")]
payload = sum(int(r) * int(n) for _, r, n, _ in rows)

out = [
 "// GENERATED by work/gen_infodat.py -- do not edit by hand.",
 "//",
 "// info.dat section layout for runblack.exe v1.0, recovered from the loader",
 "// (sub_425250) by work/info_layout.py: the sections in file order, the bytes",
 "// each record reads (parent blocks included), the record count, and the",
 "// in-memory element stride the record is copied into at +16.",
 "// See docs/info-dat.md.",
 "#pragma once",
 "#include <cstdint>",
 "",
 "namespace infodat {",
 "",
 "enum Section : uint16_t {",
]
out += [f"    {name}," for name, *_ in rows]
out += ["    SECTION_COUNT", "};", "",
        "struct SectionLayout { const char* name; uint32_t record_bytes, count, stride; };", "",
        "inline constexpr SectionLayout kLayout[SECTION_COUNT] = {"]
out += [f'    {{ "{name}", {r}, {n}, {s} }},' for name, r, n, s in rows]
out += ["};", "",
        f"inline constexpr uint32_t kPayloadBytes = {payload};  // must equal the header's size field",
        "", "} // namespace infodat", ""]
dst = os.path.join(HERE, "../src/include/black/InfoDatLayout.gen.h")
open(dst, "w", newline="\n").write("\n".join(out))
print(f"{len(rows)} sections, {payload} payload bytes -> {os.path.relpath(dst, HERE)}")
