"""The creature-chooser predicates, per class, as the v1.0 binary implements them.

For each class below, read its vftable (IDA's RTTI-derived ??_7 label) at every
slot CreatureDispatch.gen.cpp dispatches, and classify the implementation:
a constant (`return 0;` / `return 1;`) or code. Writes
src/viewer/PredicateTable.gen.h for test_chooser, which constructs our classes
and checks they give the binary's constant answers.

    py -3.11 work/gen_predicate_table.py <bw.exe.i64>
"""
import re
import sys

import idapro
import ida_auto
import ida_bytes
import ida_hexrays
import ida_name
import idc

CLASSES = ["Villager", "Abode", "StoragePit", "TownCentre", "Tree", "Field", "FishFarm",
           "Rock", "BigForest", "Creature", "Bonfire", "Feature"]

idapro.open_database(sys.argv[1] if len(sys.argv) > 1 else "E:/ida/work/bw.exe.i64", True)
ida_auto.auto_wait()
ida_hexrays.init_hexrays_plugin()

gen = open("src/core/CreatureDispatch.gen.cpp").read()
slots = sorted(int(x) for x in re.findall(r"case (\d+):", gen))
kinds = {}


def kind(a):
    if a not in kinds:
        try:
            t = str(ida_hexrays.decompile(a))
        except Exception:
            t = ""
        body = re.sub(r"\s+", " ", t[t.find("{"):]).strip() if "{" in t else ""
        m = re.fullmatch(r"\{ return (\d+); \}", body)
        kinds[a] = int(m.group(1)) if m else -1
    return kinds[a]


rows = []
for cls in CLASSES:
    ea = ida_name.get_name_ea(idc.BADADDR, f"??_7{cls}@@6B@")
    if ea == idc.BADADDR:
        raise SystemExit(f"no vftable for {cls}")
    for s in slots:
        a = ida_bytes.get_dword(ea + 4 * s)
        rows.append(f'    {{"{cls}", {s}, {kind(a)}, 0x{a:X}}},')

out = """#pragma once
// GENERATED by work/gen_predicate_table.py -- do not edit.
// Per class and predicate slot: the binary's constant answer (0/1), or -1 where
// the implementation is code, with its address.
#include <cstdint>

struct PredicateRow { const char* cls; int slot; int value; uint32_t addr; };

inline constexpr PredicateRow kPredicateTable[] = {
""" + "\n".join(rows) + "\n};\n"
open("src/viewer/PredicateTable.gen.h", "w", newline="\n").write(out)
print(len(rows), "rows,", sum(1 for r in rows if ", -1, " not in r), "constant")
